// js-host-world.ts — ONE CONSTRUCTION OF THE RUNTIME WORLD, shared by the
// test file and by any later reader.
//
// WHY IT IS A SEPARATE WORLD FROM test/js-corpus-world.ts, measured rather than
// preferred. The five call fixtures import nothing from node and reference no
// runtime global outside a comment, so the runtime layer would have derived
// exactly zero rows there. Adding a sixth file to that corpus would move every
// named set and every cost pin in the suite at once — the merge hazard HANDOFF
// records under *Running items in parallel* — for a layer that needs none of
// the call graph's fixtures to have a question.
//
// PACKS FIRST, FACTS AFTER, AND ONE `load`. `r.load()` re-evaluates, so a world
// that loads nine packs runs the fixpoint nine times to produce one answer;
// test/js-corpus-world.ts measured that at 16.9 s against 10.0 s and this world
// is built the same way.

import assert from 'node:assert/strict';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { Rofl } from '../src/api.ts';
import { scan } from '../scanners/js_ast.ts';

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
export const read = (p: string): string => fs.readFileSync(path.join(ROOT, p), 'utf8');

const FIX = 'test/fixtures/js-host/';
export const FILES: [string, string][] = [
  ['runtime.mjs', FIX + 'runtime.mjs'],
  ['shadow.mjs', FIX + 'shadow.mjs'],
  ['clock.mjs', FIX + 'clock.mjs'],
];

/** the packs this world holds, and the reason for each one that is not
 *  obviously this layer's:
 *    js-kinds       the base vocabulary every world here loads
 *    js-callgraph   `callee_of`, `call_site` — the runtime sites are calls
 *    js-dataflow    `binds_name`, `param_of`, `selects[flow]`, `ident_in`
 *    js-modules     `resolved_builtin`, `binding`, `site_file` — the module door
 *    js-shapes      the shape ledger js-callgraph's rules read
 *    js-statements  the statement vocabulary js-dataflow's rules read */
export const PACKS = [
  'boot.rofl',
  'facts/js-kinds.rofl', 'facts/js-callgraph.rofl', 'facts/js-dataflow.rofl',
  'facts/js-modules.rofl', 'facts/js-shapes.rofl', 'facts/js-statements.rofl',
  // THE ERA HALF, and it is here because THE BRIDGE NEEDS IT. `provides_release`
  // lands on a `release/1` generated by scanners/ts_lib.ts, and
  // `runtime_reaches_release[audit]` composes it with `reaches[audit]`, which is
  // rules/js-env.rofl's walk. A world holding the runtime axis and not the ES
  // one could declare the bridge and never evaluate it — the failure
  // rules/js-env-api.rofl already records as `two worlds that are never loaded
  // together`, and the reason this world refuses to repeat it.
  'facts/js-lib-surface.rofl', 'facts/js-env.rofl',
  'facts/js-host-surface.rofl', 'facts/js-host.rofl',
  'rules/js-structure.rofl', 'rules/js-dataflow.rofl', 'rules/js-callgraph.rofl',
  'rules/js-modules.rofl', 'rules/js-env.rofl', 'rules/js-env-api.rofl',
  'rules/js-host.rofl',
];

/** THE TWO BLIND HOST EMITTERS the modules layer needs, in the same form
 *  test/js-modules.test.ts writes them: the kernel's builtins are arithmetic
 *  and comparison only, so no rule can take a specifier apart. `str_scheme` is
 *  the one this layer depends on — it is what makes `node:fs` a
 *  `node_builtin` shape rather than a bare package. */
const qs = (s: string): string => '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
export function strFacts(s: string): string[] {
  if (s.length === 0) return [];
  const segs = s.split('/');
  const out = [`str_char0[code](${qs(s)}, ${qs(s[0] as string)}).`, `str_segs[code](${qs(s)}, ${segs.length}).`];
  segs.forEach((g, i) => out.push(`str_seg[code](${qs(s)}, ${i}, ${qs(g)}).`));
  const c = s.indexOf(':');
  if (c > 0) out.push(`str_scheme[code](${qs(s)}, ${qs(s.slice(0, c))}).`);
  return out;
}

/** every specifier the fixtures actually write, cut for the string relations.
 *  Read off the source rather than listed by hand, so a new import in a fixture
 *  cannot silently go unresolvable. */
function specifierFacts(sources: string[]): string[] {
  const out = new Set<string>();
  for (const src of sources)
    for (const m of src.matchAll(/from\s+'([^']+)'/g)) for (const f of strFacts(m[1])) out.add(f);
  return [...out];
}

export type Mut = { file: string; find: string; replace: string };
export interface World { q: (l: string) => string[][]; n: (l: string) => number }

const unq = (s: string): string => (s.startsWith('"') && s.endsWith('"') ? s.slice(1, -1) : s);

export function build(muts: Mut[] = []): World {
  const r = new Rofl();
  const texts = PACKS.map((f) => {
    let t = read(f);
    for (const m of muts) if (m.file === f) {
      assert.ok(t.includes(m.find), `mutation anchor absent in ${f}: ${m.find}`);
      t = t.replace(m.find, m.replace);
    }
    return t;
  });
  const res = r.load(texts.join('\n'));
  assert.ok(res.ok, `world REJECTED:\n${res.diagnostics.slice(0, 6).join('\n')}`);
  const sources = FILES.map(([, disk]) => read(disk));
  for (const [i, [logical]] of FILES.entries()) {
    const f = r.assert(scan(sources[i], { file: logical }).facts.join('\n'));
    assert.ok(f.ok, `${logical} facts REJECTED:\n${f.diagnostics.slice(0, 4).join('\n')}`);
  }
  const s = r.assert(specifierFacts(sources).join('\n'));
  assert.ok(s.ok, `specifier facts REJECTED:\n${s.diagnostics.slice(0, 4).join('\n')}`);
  r.evaluate(40_000_000);

  const q = (lit: string): string[][] => {
    const out = r.query(lit);
    assert.equal(out.error, undefined, `query ${lit}: ${out.error}`);
    assert.equal(out.partial, false, `query ${lit} hit a budget`);
    assert.equal(out.unpopulatable, false, `query ${lit}: nothing in this world can populate it`);
    const seen = new Set<string>();
    const order = [...lit.matchAll(/\b([A-Z][A-Za-z0-9_]*)\b/g)].map((m) => m[1])
      .filter((v) => (seen.has(v) ? false : (seen.add(v), true)));
    return out.rows.map((row) => order.map((v) => unq(row.bindings[v] ?? '')));
  };
  return { q, n: (l) => q(l).length };
}

let BASE: World | undefined;
export const base = (): World => (BASE ??= build());
export { ROOT };
