// THE GENERATED LEXER AGAINST THE RULES IT WAS GENERATED FROM.
//
// `scanners/ring1_lexgen.ts` compiles ring1's character automaton into Rust by
// READING `examples/ring1/ring1.rofl` — the states, the transitions, the
// guards and the character table are all recovered from parsed clauses, so
// changing the syntax stays a change to RULES. That is the whole point of the
// tower (f_the_rule_syntax_is_provably_sugar), and it is also the whole risk:
// a generator that quietly mis-reads a rule produces a lexer that COMPILES.
//
// So ring1 is the oracle. For every file below, the automaton's state at every
// position must equal `st/2` as the rules derive it. One position is enough to
// fail.
//
// IT HAS ALREADY CAUGHT ONE. The first draft read a functor's name from `.f`
// where the field is `.name`, so every `I1 is I + 1` offset collapsed to zero
// and `opens_cmt` became `kind(i)=dash & kind(i)=dash` — a two-character
// lookahead flattened into one, which is a WRONG automaton that compiles and
// passes a casual eye. It was caught by reading the generator's own summary
// line, before this test existed; the test is what makes that permanent.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { Rofl } from '../src/api.ts';
import { extract, type Cond } from '../scanners/ring1_lexgen.ts';

const REPO = fs.realpathSync(new URL('..', import.meta.url).pathname);
const read = (p: string): string => fs.readFileSync(path.join(REPO, p), 'utf8');
const BUDGET = 4_000_000_000;

// A spread of shapes rather than a spread of sizes: a comment-only file, one
// with strings and escapes, one with none, and the character table itself.
const FILES = [
  'examples/counter.rofl',
  'rules/policies/authority.rofl',
  'examples/tm.rofl',
  'examples/ring1/charclass.rofl',
  'rules/js-dataflow.rofl',
];

const a = extract();
const size = (c: Cond): number => (c.k === 'and' ? c.cs.reduce((n, x) => n + size(x), 0) : c.k === 'true' ? 0 : 1);
const holds = (c: Cond, k: string[], i: number): boolean => {
  switch (c.k) {
    case 'true': return true;
    case 'kind': { const j = i + c.off; return j >= 0 && j < k.length && k[j] === c.kind; }
    case 'not': return !holds(c.c, k, i);
    case 'and': return c.cs.length === 0 ? false : c.cs.every((x) => holds(x, k, i));
  }
};
function generated(src: string): string[] {
  const k = [...src].map((c) => a.charKinds.get(c) ?? 'other');
  const out: string[] = [];
  let s = a.start;
  for (let i = 0; i < k.length; i++) {
    out.push(s);
    const ms = (a.moves.get(s) ?? []).slice().sort((x, y) => size(y.cond) - size(x.cond));
    let next = s;
    for (const m of ms) if (holds(m.cond, k, i)) { next = m.to; break; }
    s = next;
  }
  return out;
}
function fromRules(src: string): Map<number, string> {
  const w = new Rofl({ space: 20_000_000 });
  for (const p of ['boot.rofl', 'examples/ring1/charclass.rofl', 'examples/ring1/ring1.rofl']) {
    w.load(read(p), { budget: BUDGET });
  }
  w.assert(`src(${JSON.stringify(src)}).`);
  w.evaluate(BUDGET);
  const out = new Map<number, string>();
  for (const row of w.query('st(I, S)').rows) out.set(Number(row.bindings.I), String(row.bindings.S));
  return out;
}

test('the extracted automaton is the one the rules describe', () => {
  assert.ok(a.states.length >= 2, 'an automaton with fewer than two states is not one');
  assert.ok(a.charKinds.size > 50, `only ${a.charKinds.size} characters classified`);
  const moves = [...a.moves.values()].reduce((n, v) => n + v.length, 0);
  assert.equal(moves, 9, 'ring1 has nine step/3 clauses; a different count means the rules moved');
});

for (const f of FILES) {
  test(`generated lexer agrees with the rules, position for position: ${f}`, () => {
    const src = read(f);
    const truth = fromRules(src);
    const mine = generated(src);
    assert.ok(truth.size > 100, `${f}: only ${truth.size} positions, too few to prove anything`);
    for (const [i, s] of truth) {
      assert.equal(mine[i], s,
        `${f}: position ${i} (${JSON.stringify(src[i])}) — rules say ${s}, generated says ${mine[i]}`);
    }
  });
}

test('the generated Rust is in the tree and was produced from these rules', () => {
  const rs = read('rust/rofl/src/ring1_lexer.rs');
  assert.match(rs, /GENERATED by scanners\/ring1_lexgen\.ts/);
  for (const st of a.states) {
    assert.ok(rs.includes(`State::${st.replace(/^./, (c) => c.toUpperCase())}`),
      `state ${st} is in the rules and not in the generated file — regenerate`);
  }
});
