// GENERATED by scanners/ring1_lexgen.ts from examples/ring1/ring1.rofl
// and examples/ring1/charclass.rofl. Do not edit: edit the RULES and
// re-run the generator. The oracle for this file is ring1 itself —
// test/ring1-lexgen.test.ts asserts position-for-position agreement.

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Kind { At, Backslash, Bang, Colon, Comma, Dash, Digit, Dollar, Dot, Eq, Gt, Lbrack, Lower, Lpar, Lt, Nl, Plus, Quote, Rbrack, Rpar, Slash, Space, Star, Upper, Other }

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum State { Cmt, Code, Esc, Str }

/// The character table, from the `cls/2` facts.
pub fn kind_of(c: char) -> Kind {
    match c {
        '@' => Kind::At,
        '\\' => Kind::Backslash,
        '!' => Kind::Bang,
        ':' => Kind::Colon,
        ',' => Kind::Comma,
        '-' => Kind::Dash,
        '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' => Kind::Digit,
        '$' => Kind::Dollar,
        '.' => Kind::Dot,
        '=' => Kind::Eq,
        '>' => Kind::Gt,
        '[' => Kind::Lbrack,
        'a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z' => Kind::Lower,
        '(' => Kind::Lpar,
        '<' => Kind::Lt,
        '\n' => Kind::Nl,
        '+' => Kind::Plus,
        '"' => Kind::Quote,
        ']' => Kind::Rbrack,
        ')' => Kind::Rpar,
        '/' => Kind::Slash,
        '\t' | '\r' | ' ' => Kind::Space,
        '*' => Kind::Star,
        'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'J' | 'K' | 'L' | 'M' | 'N' | 'O' | 'P' | 'Q' | 'R' | 'S' | 'T' | 'U' | 'V' | 'W' | 'X' | 'Y' | 'Z' | '_' => Kind::Upper,
        _ => Kind::Other,
    }
}

/// One transition of the automaton, from the `step/3` clauses.
pub fn step(k: &[Kind], i: usize, s: State) -> State {
    let at = |o: i64| -> Option<Kind> {
        let j = i as i64 + o;
        if j < 0 || j as usize >= k.len() { None } else { Some(k[j as usize]) }
    };
    match s {
        State::Cmt => {
            if at(0) == Some(Kind::Nl) { return State::Code; }
            if !(at(0) == Some(Kind::Nl)) { return State::Cmt; }
            State::Cmt
        }
        State::Code => {
            if at(0) == Some(Kind::Dash) && at(1) == Some(Kind::Dash) && !(at(0) == Some(Kind::Quote)) { return State::Cmt; }
            if !(at(0) == Some(Kind::Quote)) && !(at(0) == Some(Kind::Dash) && at(1) == Some(Kind::Dash)) { return State::Code; }
            if at(0) == Some(Kind::Quote) { return State::Str; }
            State::Code
        }
        State::Esc => {
            State::Str
        }
        State::Str => {
            if !(at(0) == Some(Kind::Quote)) && !(at(0) == Some(Kind::Backslash)) { return State::Str; }
            if at(0) == Some(Kind::Backslash) { return State::Esc; }
            if at(0) == Some(Kind::Quote) { return State::Code; }
            State::Str
        }
    }
}

/// `st/2` for every position: the state the automaton is IN at i.
pub fn states(src: &str) -> Vec<State> {
    let k: Vec<Kind> = src.chars().map(kind_of).collect();
    let mut out = Vec::with_capacity(k.len());
    let mut s = State::Code;
    for i in 0..k.len() {
        out.push(s);
        s = step(&k, i, s);
    }
    out
}
