// GENERATED by scanners/ring1_spangen.ts from examples/ring1/ring1.rofl.
// Do not edit: edit the RULES and re-run the generator. These are TABLES;
// the driver that walks them is `ring1_tok.rs` and is written once.
// The oracle is ring1 itself — test/ring1-spangen.test.ts asserts that the
// set of token spans equals the set the rules derive.
use crate::ring1_tok::{Prod, Rel, Step as S, Test as T, Valued};

pub const RELS: &[Rel] = &[
    Rel { name: "len", prods: &[
        Prod::Chain { steps: &[], end_off: None },
    ] },
    Rel { name: "opens_str", prods: &[
        Prod::Chain { steps: &[S::Test(0, T::Kind(0, "quote"))], end_off: None },
    ] },
    Rel { name: "opens_cmt", prods: &[
        Prod::Chain { steps: &[S::Test(0, T::Kind(0, "dash")), S::Test(0, T::Kind(1, "dash"))], end_off: None },
    ] },
    Rel { name: "code_at", prods: &[
        Prod::Chain { steps: &[S::Test(0, T::State(0, "code"))], end_off: None },
    ] },
    Rel { name: "str_open", prods: &[
        Prod::Chain { steps: &[S::Test(0, T::Kind(0, "quote")), S::Test(0, T::State(0, "code"))], end_off: None },
    ] },
    Rel { name: "str_close", prods: &[
        Prod::Chain { steps: &[S::Test(0, T::State(0, "str")), S::Test(0, T::Kind(0, "quote"))], end_off: None },
    ] },
    Rel { name: "strtok", prods: &[
        Prod::Chain { steps: &[S::Test(0, T::Pred(0, "str_open")), S::Search(T::Pred(0, "str_close"))], end_off: None },
    ] },
    Rel { name: "wordch", prods: &[
        Prod::Chain { steps: &[S::Test(0, T::Pred(0, "code_at")), S::Test(0, T::Kind(0, "lower"))], end_off: None },
        Prod::Chain { steps: &[S::Test(0, T::Pred(0, "code_at")), S::Test(0, T::Kind(0, "upper"))], end_off: None },
        Prod::Chain { steps: &[S::Test(0, T::Pred(0, "code_at")), S::Test(0, T::Kind(0, "digit"))], end_off: None },
    ] },
    Rel { name: "prevword", prods: &[
        Prod::Chain { steps: &[S::Test(0, T::Pred(-1, "wordch"))], end_off: None },
    ] },
    Rel { name: "word_start", prods: &[
        Prod::Chain { steps: &[S::Test(0, T::Pred(0, "wordch")), S::Test(0, T::Not(&T::Pred(0, "prevword"))), S::Test(0, T::Not(&T::Pred(0, "dollar_before")))], end_off: None },
        Prod::Chain { steps: &[S::Test(0, T::Kind(0, "dollar")), S::Test(0, T::Pred(0, "code_at"))], end_off: None },
    ] },
    Rel { name: "dollar_before", prods: &[
        Prod::Chain { steps: &[S::Test(0, T::Kind(-1, "dollar")), S::Test(0, T::Pred(-1, "code_at"))], end_off: None },
    ] },
    Rel { name: "wext", prods: &[
        Prod::Chain { steps: &[S::Test(0, T::Pred(0, "word_start"))], end_off: None },
        Prod::While { step: &[T::Pred(1, "wordch")] },
    ] },
    Rel { name: "word", prods: &[
        Prod::Chain { steps: &[S::Consume("wext"), S::Test(1, T::Not(&T::Pred(1, "wordch")))], end_off: None },
    ] },
    Rel { name: "neck", prods: &[
        Prod::Chain { steps: &[S::Test(0, T::Kind(0, "colon")), S::Test(0, T::Pred(0, "code_at")), S::Test(0, T::Kind(1, "dash"))], end_off: Some(1) },
    ] },
    Rel { name: "identtok", prods: &[
        Prod::Chain { steps: &[S::Consume("word"), S::Test(0, T::Kind(0, "lower"))], end_off: None },
        Prod::Chain { steps: &[S::Consume("word"), S::Test(0, T::Kind(0, "dollar"))], end_off: None },
    ] },
    Rel { name: "vartok", prods: &[
        Prod::Chain { steps: &[S::Consume("word"), S::Test(0, T::Kind(0, "upper"))], end_off: None },
    ] },
    Rel { name: "inttok", prods: &[
        Prod::Chain { steps: &[S::Consume("word"), S::Test(0, T::Kind(0, "digit"))], end_off: None },
    ] },
    Rel { name: "kw_not", prods: &[
        Prod::Chain { steps: &[S::Consume("word"), S::Test(1, T::Char(-2, "n")), S::Test(1, T::Char(-1, "o")), S::Test(1, T::Char(0, "t"))], end_off: Some(-2) },
    ] },
    Rel { name: "kw_is", prods: &[
        Prod::Chain { steps: &[S::Consume("word"), S::Test(1, T::Char(-1, "i")), S::Test(1, T::Char(0, "s"))], end_off: Some(-1) },
    ] },
    Rel { name: "kw_mod", prods: &[
        Prod::Chain { steps: &[S::Consume("word"), S::Test(1, T::Char(-2, "m")), S::Test(1, T::Char(-1, "o")), S::Test(1, T::Char(0, "d"))], end_off: Some(-2) },
    ] },
    Rel { name: "kw_init", prods: &[
        Prod::Chain { steps: &[S::Consume("word"), S::Test(1, T::Char(-3, "i")), S::Test(1, T::Char(-2, "n")), S::Test(1, T::Char(-1, "i")), S::Test(1, T::Char(0, "t"))], end_off: Some(-3) },
    ] },
    Rel { name: "kw_now", prods: &[
        Prod::Chain { steps: &[S::Consume("word"), S::Test(1, T::Char(-2, "n")), S::Test(1, T::Char(-1, "o")), S::Test(1, T::Char(0, "w"))], end_off: Some(-2) },
    ] },
    Rel { name: "kw_next", prods: &[
        Prod::Chain { steps: &[S::Consume("word"), S::Test(1, T::Char(-3, "n")), S::Test(1, T::Char(-2, "e")), S::Test(1, T::Char(-1, "x")), S::Test(1, T::Char(0, "t"))], end_off: Some(-3) },
    ] },
    Rel { name: "keyword", prods: &[
        Prod::Chain { steps: &[S::Test(0, T::Pred(0, "kw_not"))], end_off: None },
    ] },
    Rel { name: "op2", prods: &[
        Prod::Chain { steps: &[S::Test(0, T::Kind(0, "bang")), S::Test(0, T::Kind(1, "eq")), S::Test(0, T::Pred(0, "code_at"))], end_off: Some(1) },
        Prod::Chain { steps: &[S::Test(0, T::Kind(0, "lt")), S::Test(0, T::Kind(1, "eq")), S::Test(0, T::Pred(0, "code_at"))], end_off: Some(1) },
        Prod::Chain { steps: &[S::Test(0, T::Kind(0, "gt")), S::Test(0, T::Kind(1, "eq")), S::Test(0, T::Pred(0, "code_at"))], end_off: Some(1) },
    ] },
    Rel { name: "arithtok", prods: &[
        Prod::Chain { steps: &[S::Test(0, T::Kind(0, "plus")), S::Test(0, T::Pred(0, "code_at"))], end_off: None },
        Prod::Chain { steps: &[S::Test(0, T::Kind(0, "star")), S::Test(0, T::Pred(0, "code_at"))], end_off: None },
        Prod::Chain { steps: &[S::Test(0, T::Kind(0, "slash")), S::Test(0, T::Pred(0, "code_at"))], end_off: None },
        Prod::Chain { steps: &[S::Test(0, T::Pred(0, "kw_mod")), S::Consume("word")], end_off: None },
        Prod::Chain { steps: &[S::Test(0, T::Kind(0, "dash")), S::Test(0, T::Pred(0, "code_at")), S::Test(0, T::Not(&T::Pred(0, "opens_cmt"))), S::Test(0, T::Not(&T::Kind(-1, "colon")))], end_off: None },
    ] },
    Rel { name: "white", prods: &[
        Prod::Chain { steps: &[S::Test(0, T::Kind(0, "space"))], end_off: None },
        Prod::Chain { steps: &[S::Test(0, T::Kind(0, "nl"))], end_off: None },
        Prod::Chain { steps: &[S::Test(0, T::Pred(0, "opens_cmt"))], end_off: None },
        Prod::Chain { steps: &[S::Test(0, T::Pred(-1, "opens_cmt"))], end_off: None },
    ] },
    Rel { name: "optok", prods: &[
        Prod::Chain { steps: &[S::Consume("op2")], end_off: None },
        Prod::Chain { steps: &[S::Test(0, T::Kind(0, "eq")), S::Test(0, T::Pred(0, "code_at")), S::Test(0, T::Not(&T::Pred(0, "consumed"))), S::Test(0, T::Not(&T::Pred(0, "starts_op2")))], end_off: None },
        Prod::Chain { steps: &[S::Test(0, T::Kind(0, "lt")), S::Test(0, T::Pred(0, "code_at")), S::Test(0, T::Not(&T::Pred(0, "consumed"))), S::Test(0, T::Not(&T::Pred(0, "starts_op2")))], end_off: None },
        Prod::Chain { steps: &[S::Test(0, T::Kind(0, "gt")), S::Test(0, T::Pred(0, "code_at")), S::Test(0, T::Not(&T::Pred(0, "consumed"))), S::Test(0, T::Not(&T::Pred(0, "starts_op2")))], end_off: None },
        Prod::Chain { steps: &[S::Test(0, T::Pred(0, "kw_is")), S::Consume("word")], end_off: None },
    ] },
    Rel { name: "tok", prods: &[
        Prod::Chain { steps: &[S::Consume("word")], end_off: None },
        Prod::Chain { steps: &[S::Consume("strtok")], end_off: None },
        Prod::Chain { steps: &[S::Valued("punct")], end_off: None },
        Prod::Chain { steps: &[S::Consume("neck")], end_off: None },
        Prod::Chain { steps: &[S::Consume("optok")], end_off: None },
        Prod::Chain { steps: &[S::Consume("arithtok")], end_off: None },
    ] },
    Rel { name: "tok_text", prods: &[
        Prod::Chain { steps: &[S::Consume("tok")], end_off: None },
    ] },
];

pub const VALUED: &[Valued] = &[
    Valued { name: "punct", cases: &[
        (&[T::Kind(0, "lpar"), T::Pred(0, "code_at")], "lpar"),
        (&[T::Kind(0, "rpar"), T::Pred(0, "code_at")], "rpar"),
        (&[T::Kind(0, "lbrack"), T::Pred(0, "code_at")], "lbrack"),
        (&[T::Kind(0, "rbrack"), T::Pred(0, "code_at")], "rbrack"),
        (&[T::Kind(0, "comma"), T::Pred(0, "code_at")], "comma"),
        (&[T::Kind(0, "dot"), T::Pred(0, "code_at")], "dot"),
        (&[T::Kind(0, "at"), T::Pred(0, "code_at")], "at"),
    ] },
];

/// `(projection, span it projects, true when onto the END)`
pub const PROJECTED: &[(&str, &str, bool)] = &[
    ("consumed", "op2", true),
    ("starts_op2", "op2", false),
    ("tokstart", "tok", false),
];
