// GENERATED by scanners/ring1_predgen.ts from examples/ring1/ring1.rofl.
// Do not edit: edit the RULES and re-run the generator. The oracle is
// ring1 itself — test/ring1-predgen.test.ts compares the set of positions
// where each of these holds against the set the rules derive.
use crate::ring1_lexer::{kind_of, states, Kind, State};

/// The source as the predicates see it: a class and a state per position.
pub struct Ctx { pub k: Vec<Kind>, pub s: Vec<State> }

impl Ctx {
    pub fn new(src: &str) -> Ctx {
        Ctx { k: src.chars().map(kind_of).collect(), s: states(src) }
    }
    pub fn len(&self) -> usize { self.k.len() }
    pub fn is_empty(&self) -> bool { self.k.is_empty() }
    fn kind(&self, i: usize, o: i64) -> Option<Kind> {
        let j = i as i64 + o;
        if j < 0 || j as usize >= self.k.len() { None } else { Some(self.k[j as usize]) }
    }
    fn state(&self, i: usize, o: i64) -> Option<State> {
        let j = i as i64 + o;
        if j < 0 || j as usize >= self.s.len() { None } else { Some(self.s[j as usize]) }
    }
}

/// An offset that leaves the source is not a position, and a predicate
/// asked about one is false rather than a panic: `at(I)` in the rules is
/// exactly this check and every clause carries it.
fn wrap(i: usize, o: i64) -> usize {
    let j = i as i64 + o;
    if j < 0 { usize::MAX } else { j as usize }
}

/// `opens_str/1`, 1 clause — a disjunction.
pub fn p_opens_str(c: &Ctx, i: usize) -> bool {
    if i >= c.len() { return false; }
    (c.kind(i, 0) == Some(Kind::Quote))
}

/// `opens_cmt/1`, 1 clause — a disjunction.
pub fn p_opens_cmt(c: &Ctx, i: usize) -> bool {
    if i >= c.len() { return false; }
    (c.kind(i, 0) == Some(Kind::Dash) && c.kind(i, 1) == Some(Kind::Dash))
}

/// `code_at/1`, 1 clause — a disjunction.
pub fn p_code_at(c: &Ctx, i: usize) -> bool {
    if i >= c.len() { return false; }
    (c.state(i, 0) == Some(State::Code))
}

/// `str_open/1`, 1 clause — a disjunction.
pub fn p_str_open(c: &Ctx, i: usize) -> bool {
    if i >= c.len() { return false; }
    (c.kind(i, 0) == Some(Kind::Quote) && c.state(i, 0) == Some(State::Code))
}

/// `str_close/1`, 1 clause — a disjunction.
pub fn p_str_close(c: &Ctx, i: usize) -> bool {
    if i >= c.len() { return false; }
    (c.state(i, 0) == Some(State::Str) && c.kind(i, 0) == Some(Kind::Quote))
}

/// `wordch/1`, 3 clauses — a disjunction.
pub fn p_wordch(c: &Ctx, i: usize) -> bool {
    if i >= c.len() { return false; }
    (p_code_at(c, wrap(i, 0)) && c.kind(i, 0) == Some(Kind::Lower))
        || (p_code_at(c, wrap(i, 0)) && c.kind(i, 0) == Some(Kind::Upper))
        || (p_code_at(c, wrap(i, 0)) && c.kind(i, 0) == Some(Kind::Digit))
}

/// `prevword/1`, 1 clause — a disjunction.
pub fn p_prevword(c: &Ctx, i: usize) -> bool {
    if i >= c.len() { return false; }
    (p_wordch(c, wrap(i, -1)))
}

/// `dollar_before/1`, 1 clause — a disjunction.
pub fn p_dollar_before(c: &Ctx, i: usize) -> bool {
    if i >= c.len() { return false; }
    (c.kind(i, -1) == Some(Kind::Dollar) && p_code_at(c, wrap(i, -1)))
}

/// `word_start/1`, 2 clauses — a disjunction.
pub fn p_word_start(c: &Ctx, i: usize) -> bool {
    if i >= c.len() { return false; }
    (p_wordch(c, wrap(i, 0)) && !(p_prevword(c, wrap(i, 0))) && !(p_dollar_before(c, wrap(i, 0))))
        || (c.kind(i, 0) == Some(Kind::Dollar) && p_code_at(c, wrap(i, 0)))
}

/// `white/1`, 4 clauses — a disjunction.
pub fn p_white(c: &Ctx, i: usize) -> bool {
    if i >= c.len() { return false; }
    (c.kind(i, 0) == Some(Kind::Space))
        || (c.kind(i, 0) == Some(Kind::Nl))
        || (p_opens_cmt(c, wrap(i, 0)))
        || (p_opens_cmt(c, wrap(i, -1)))
}

/// Every predicate by name, so a test can ask for one without knowing it.
pub fn by_name(n: &str, c: &Ctx, i: usize) -> Option<bool> {
    match n {
        "opens_str" => Some(p_opens_str(c, i)),
        "opens_cmt" => Some(p_opens_cmt(c, i)),
        "code_at" => Some(p_code_at(c, i)),
        "str_open" => Some(p_str_open(c, i)),
        "str_close" => Some(p_str_close(c, i)),
        "wordch" => Some(p_wordch(c, i)),
        "prevword" => Some(p_prevword(c, i)),
        "dollar_before" => Some(p_dollar_before(c, i)),
        "word_start" => Some(p_word_start(c, i)),
        "white" => Some(p_white(c, i)),
        _ => None,
    }
}

/// The names this module answers for.
pub const NAMES: [&str; 10] = ["opens_str", "opens_cmt", "code_at", "str_open", "str_close", "wordch", "prevword", "dollar_before", "word_start", "white"];
