// A generator, not part of the notebook tool: two facts the ledger's own
// clauses cannot state about themselves, brought in from outside because
// nothing in `facts/findings.rofl` or `rules/findings.rofl` can.
//
//   path_exists(P)     the host filesystem, which the reader never asks.
//   reason_len(F, N)   the length of a dismissed finding's Reason string;
//                      the sentence form has no length/substring builtin
//                      (only "X is Y", "X differs from Y", ">", "+"), so a
//                      check on a string's shape has to arrive as a number.
//
// Run: node --experimental-strip-types examples/notebook/gen_ledger_facts.ts
// Writes: examples/notebook/ledger_facts.rofl

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import * as path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '../..');
const findings = readFileSync(path.join(ROOT, 'facts/findings.rofl'), 'utf8');

const paths = new Set<string>();
for (const m of findings.matchAll(/^(?:addressed_by|artifact_removed)\([a-zA-Z0-9_]+,\s*"([^"]*)"\)/gm)) {
  paths.add(m[1]);
}
const pathLines = [...paths].sort()
  .filter((p) => existsSync(path.join(ROOT, p)))
  .map((p) => `path_exists("${p}").`);

// Reason is written two ways in the ledger: a bare atom (`bun_is_ci_only`) or
// a quoted string (`"the cost gates were removed: ..."`). Neither the sentence
// form nor plain Datalog gives a uniform way to ask "how long is this term
// regardless of which kind it is", so the split is measured here too.
const reasonLines: string[] = [];
const shapeLines: string[] = [];
// One dismissed(...) call in the ledger wraps its Reason onto a second,
// indented line (facts/findings.rofl:4598) -- every other occurrence is one
// line -- so the gap after the comma is \s*, not a literal space.
for (const m of findings.matchAll(/^dismissed\((f_[a-zA-Z0-9_]+),\s*(?:"((?:[^"\\]|\\.)*)"|([a-z][a-zA-Z0-9_]*))\)/gm)) {
  const [, , quoted, atom] = m;
  const text = quoted ?? atom;
  reasonLines.push(`reason_len(${m[1]}, ${text.length}).`);
  // A plain .rofl file's atoms are bare words, unlike the backtick-quoted
  // atoms of the Markdown sentence form (docs/md-world.md) -- backticks
  // here are a syntax error in the reader this file loads through.
  shapeLines.push(`reason_shape(${m[1]}, ${quoted !== undefined ? 'string' : 'atom'}).`);
}

const out = `-- generated by examples/notebook/gen_ledger_facts.ts; do not hand-edit.
-- path_exists(P): a path cited by addressed_by/artifact_removed in
-- facts/findings.rofl that exists on disk as of the run named above.
-- Absence from this file means either it does not exist, or it was never
-- cited -- the notebook only asks about paths it also cites.
-- reason_len(F, N): the character length of F's dismissed(F, Reason) term,
-- string or atom either way.
-- reason_shape(F, string|atom): which of the two Reason wrote as.

${pathLines.join('\n')}

${reasonLines.join('\n')}

${shapeLines.join('\n')}
`;
writeFileSync(path.join(ROOT, 'examples/notebook/ledger_facts.rofl'), out);
console.log(`${paths.size} cited paths, ${pathLines.length} exist; ${reasonLines.length} dismissed reasons measured`);
console.log('wrote examples/notebook/ledger_facts.rofl');
