[package]
name = "rofl"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
serde_json = "1"

[lib]
name = "rofl"
path = "src/lib.rs"

[[bin]]
name = "rofl-eval"
path = "src/bin/rofl_eval.rs"

[[bin]]
name = "ring1-lex"
path = "src/bin/ring1_lex.rs"

[[bin]]
name = "ring1-preds"
path = "src/bin/ring1_preds_dump.rs"

[[bin]]
name = "ring1-tokens"
path = "src/bin/ring1_tokens_dump.rs"

[[bin]]
name = "rofl-lex"
path = "src/bin/rofl_lex_dump.rs"
