// scanners/materialize.ts — incremental fact materialization: a source tree
// becomes a directory of .rofl fact files, one per source file, keyed by
// content hash. Unchanged files are never re-parsed; deleted files lose their
// fact file. The manifest is the single source of truth for what is current.

import * as fs from 'node:fs';
import * as path from 'node:path';
import * as crypto from 'node:crypto';
import { extractFacts, SCANNER_PERSP } from './js.ts';

export const SCANNER_WHO = 'scanner';
export const PREAMBLE_FILE = '_authority.rofl';
const MANIFEST_FILE = 'manifest.json';
const PREAMBLE =
  `-- grants the scanner write authority over the [${SCANNER_PERSP}] perspective.\n` +
  `-- load this file first, WITHOUT a who; load fact files with who=${SCANNER_WHO}.\n` +
  `authority(${SCANNER_PERSP}, ${SCANNER_WHO}).\n`;

export interface ScanReport {
  scanned: string[];    // parsed this run (new or changed)
  unchanged: string[];  // content hash hit, skipped
  removed: string[];    // source gone, fact file deleted
  factFiles: string[];  // absolute-ish paths, preamble first (load order)
}

interface Manifest { version: 1; files: Record<string, { hash: string; out: string }>; }

const EXTS = new Set(['.js', '.mjs', '.cjs', '.jsx', '.ts', '.tsx', '.mts', '.cts']);
const SKIP_DIRS = new Set(['node_modules', 'dist', 'build', 'coverage']);

function listSources(root: string, outAbs: string): string[] {
  const out: string[] = [];
  const rec = (dir: string): void => {
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, e.name);
      if (e.isDirectory()) {
        if (SKIP_DIRS.has(e.name) || e.name.startsWith('.') || path.resolve(full) === outAbs) continue;
        rec(full);
      } else if (EXTS.has(path.extname(e.name)) && !e.name.endsWith('.d.ts')) {
        out.push(path.relative(root, full).split(path.sep).join('/'));
      }
    }
  };
  rec(root);
  return out.sort();
}

function slug(relPath: string): string {
  const s = relPath.replace(/\//g, '__').replace(/[^A-Za-z0-9._-]/g, '_');
  const h = crypto.createHash('sha256').update(relPath).digest('hex').slice(0, 8);
  return `${s}.${h}.rofl`;
}

export function materialize(srcDir: string, outDir: string): ScanReport {
  fs.mkdirSync(outDir, { recursive: true });
  const outAbs = path.resolve(outDir);
  const manifestPath = path.join(outDir, MANIFEST_FILE);
  let manifest: Manifest = { version: 1, files: {} };
  if (fs.existsSync(manifestPath)) {
    try { manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8')) as Manifest; }
    catch { manifest = { version: 1, files: {} }; }
  }
  const preamblePath = path.join(outDir, PREAMBLE_FILE);
  if (!fs.existsSync(preamblePath)) fs.writeFileSync(preamblePath, PREAMBLE);

  const report: ScanReport = { scanned: [], unchanged: [], removed: [], factFiles: [] };
  const seen = new Set<string>();
  for (const rel of listSources(srcDir, outAbs)) {
    seen.add(rel);
    const code = fs.readFileSync(path.join(srcDir, rel), 'utf8');
    const hash = crypto.createHash('sha256').update(code).digest('hex');
    const prev = manifest.files[rel];
    if (prev && prev.hash === hash && fs.existsSync(path.join(outDir, prev.out))) {
      report.unchanged.push(rel);
      continue;
    }
    const out = slug(rel);
    const facts = extractFacts(rel, code, hash.slice(0, 12));
    const header = `-- generated by scanners/js.ts from ${rel}\n-- sha256 ${hash}\n`;
    fs.writeFileSync(path.join(outDir, out), header + facts.join('\n') + '\n');
    manifest.files[rel] = { hash, out };
    report.scanned.push(rel);
  }
  for (const rel of Object.keys(manifest.files)) {
    if (!seen.has(rel)) {
      const f = path.join(outDir, manifest.files[rel].out);
      if (fs.existsSync(f)) fs.unlinkSync(f);
      delete manifest.files[rel];
      report.removed.push(rel);
    }
  }
  fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n');
  report.factFiles = [
    path.join(outDir, PREAMBLE_FILE),
    ...Object.values(manifest.files).map((f) => path.join(outDir, f.out)).sort(),
  ];
  return report;
}
