// scanners/parse_cost.ts — THE PARSE, MEASURED AND EMITTED AS FACTS.
//
// The owner asked why parsing ROFL in ROFL is slow, and asked for the answer as
// a WHY CHAIN rather than a paragraph. So this measures, and `rules/parse-cost.
// rofl` reasons: every number below is produced by running ring 1, nothing here
// is a judgement, and `npm run parsecost` regenerates the file so the model
// cannot describe a version of the code that has moved.
//
// The measurements, and why each one is taken:
//
//   reuse on / off   the same clause parsed twice, to see whether the cache
//                    saves any firing at all. It is the only way to tell an
//                    optimisation from an overhead.
//   the size sweep   one clause at five lengths, cache OFF, so the curve is the
//                    grammar's and not the cache's.
//   relAll / add     the store's two primitives, timed against a relation that
//                    grows. Which one carries the growth is the whole question.
//
//   node --experimental-strip-types scanners/parse_cost.ts > facts/parse-cost.rofl

import * as fs from 'node:fs';
import * as path from 'node:path';
import { Rofl } from '../src/api.ts';
import { Store } from '../src/store.ts';
import { image } from '../examples/ring1/demo.ts';
import type { Term } from '../src/unify.ts';

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const BUDGET = 800_000_000;
const roflStr = (s: string) => JSON.stringify(s);
/** One clause of k premises: the shortest thing that grows in one dimension. */
const clause = (k: number) => 'p(X) :- ' + Array.from({ length: k }, (_, i) => `q${i}(X)`).join(', ') + '.';

export interface Run { bytes: number; ms: number; firings: number; facts: number; }

export function runOnce(img: string, src: string, reuse: boolean): Run {
  const r = Rofl.fromSnapshot(img, { reuse });
  const t = Date.now();
  r.load(`src(${roflStr(src)}).`, { budget: BUDGET });
  r.evaluate(BUDGET);
  const ms = Date.now() - t;
  return { bytes: src.length, ms, firings: (r as unknown as { lastSteps: number }).lastSteps,
    facts: r.store.allFacts().length };
}

/** The store's two primitives against a relation of n facts. Times are in
 *  MICROSECONDS per call, because one call is well under a millisecond. */
export function storePrimitives(n: number): { addUs: number; relAllUs: number } {
  const mki = (v: number): Term => ({ k: 'i', v });
  const s = new Store();
  let t = process.hrtime.bigint();
  for (let i = 1; i <= n; i++) s.add('r', 'main', [mki(i), mki(i % 7)], { scope: 'timeless', base: true });
  const addUs = Number(process.hrtime.bigint() - t) / 1000 / n;
  const probes = 200;
  t = process.hrtime.bigint();
  for (let i = 0; i < probes; i++) s.relAll('r');
  const relAllUs = Number(process.hrtime.bigint() - t) / 1000 / probes;
  return { addUs, relAllUs };
}

const isMain = process.argv[1] && path.resolve(process.argv[1]).includes('parse_cost');
if (isMain) {
  const img = image();
  const one = clause(3);
  const on = runOnce(img, one, true);
  const off = runOnce(img, one, false);
  const sweep = [1, 4, 16, 32, 64].map((k) => runOnce(img, clause(k), false));
  const small = storePrimitives(1000);
  const big = storePrimitives(40000);

  const out: string[] = [];
  const say = (l: string) => out.push(l);
  say('-- facts/parse-cost.rofl — GENERATED by scanners/parse_cost.ts, do not edit.');
  say('--');
  say('-- Every row is a measurement of ring 1 parsing one clause. The reasoning');
  say('-- over them is rules/parse-cost.rofl; nothing here concludes anything.');
  say(`-- Taken on node ${process.version}.`);
  say('');
  say('-- THE SAME CLAUSE, PARSED TWICE: with the derived-reuse cache and without.');
  say(`cache(on, ms, ${on.ms}).`);
  say(`cache(on, firings, ${on.firings}).`);
  say(`cache(on, facts, ${on.facts}).`);
  say(`cache(off, ms, ${off.ms}).`);
  say(`cache(off, firings, ${off.firings}).`);
  say(`cache(off, facts, ${off.facts}).`);
  say('');
  say('-- ONE CLAUSE AT FIVE LENGTHS, cache off: bytes, ms, firings, store facts.');
  for (const r of sweep) say(`sweep(${r.bytes}, ${r.ms}, ${r.firings}, ${r.facts}).`);
  say('');
  say('-- THE STORE\'S TWO PRIMITIVES, microseconds per call, against a relation');
  say('-- of 1000 facts and one of 40000. Rounded: a rule cannot read a float.');
  say(`primitive(store_add, 1000, ${Math.round(small.addUs * 1000)}).`);
  say(`primitive(store_add, 40000, ${Math.round(big.addUs * 1000)}).`);
  say(`primitive(rel_all, 1000, ${Math.round(small.relAllUs * 1000)}).`);
  say(`primitive(rel_all, 40000, ${Math.round(big.relAllUs * 1000)}).`);
  say('-- (nanoseconds, so the integers stay integers)');
  say('');
  say('-- WHERE THE CODE CALLS THEM. Read off src/engine.ts by name, not by line:');
  say('-- `fingerprint` is the reuse plan hashing a relation, `candidates` is the');
  say('-- premise match falling back to a scan when the index declines.');
  say('call_site(fingerprint, rel_all).');
  say('call_site(candidates, rel_all).');
  say('in_phase(fingerprint, reuse_plan).');
  say('in_phase(candidates, fixpoint).');
  say('-- and WHY the index declines: `indexProbe` returns null when no argument');
  say('-- of the premise is bound, which is the leading premise of a chart rule.');
  say('declines(candidates, no_bound_argument).');
  fs.writeFileSync(path.join(ROOT, 'facts', 'parse-cost.rofl'), out.join('\n') + '\n');
  console.error(`facts/parse-cost.rofl written: ${out.length} lines`);
}
