// ts_lib.ts — THE STANDARD LIBRARY SURFACE, TAKEN FROM TYPESCRIPT'S OWN RECORD.
//
// `stdlib_member[audit]` in rules/js-callgraph.rofl names the residue the call
// graph cannot resolve: a member call whose receiver has a known PROTOTYPE and
// whose method is not a node in this program. `array.join`, `regexp.test`,
// `string.concat`, `bigint.toString`. Naming the residue was
// w_prototype_of_a_value; ATTRIBUTING it — saying which method that is and
// since when it has existed — is w_env_api_surface, and it needs a library the
// model does not have.
//
// IT DOES NOT NEED TO INVENT ONE. `node_modules/typescript/lib` ships 89
// `lib.es*.d.ts` files, and the ERA IS IN THE FILE NAME: `Array.prototype.at`
// is declared in `lib.es2022.array.d.ts` and nowhere earlier, `String.replaceAll`
// in `lib.es2021.string.d.ts`, `Array.prototype.join` in `lib.es5.d.ts`. That is
// TypeScript's own record of when each method landed, maintained by people who
// track the specification, and reading it is cheaper AND more trustworthy than a
// hand-written table this repository would have to keep.
//
// THE CEILING, STATED. This reads DECLARATIONS, not semantics: it says the name
// exists on that prototype from that year, and nothing about what it does. A
// method removed from a later era would not be visible (`feature_since` has no
// `feature_until` twin here for the same reason the era table does not: nothing
// in ECMAScript has been withdrawn). Overloads collapse to one row, which is
// right for a question about NAMES.
//
// PARSED WITH THE TYPESCRIPT COMPILER rather than with a regular expression,
// because the compiler is already a dependency and a regex over a declaration
// file is a model whose ceiling nobody can state.

import * as fs from 'node:fs';
import * as path from 'node:path';
import ts from 'typescript';

/** the eight prototypes this model can already name a receiver's kind for —
 *  see `kind_prototype` and `builtin_prototype` in rules/js-dataflow.rofl. A
 *  ninth here would be a row no rule reads. */
export const PROTOTYPES = new Map<string, string>([
  ['Array', 'array'], ['String', 'string'], ['Number', 'number'],
  ['Boolean', 'boolean'], ['RegExp', 'regexp'], ['BigInt', 'bigint'],
  ['Object', 'object'], ['Function', 'function'],
]);

/** `lib.es2015.core.d.ts` -> 2015, `lib.es5.d.ts` -> 2009. The years are the
 *  ones `env_rank` already uses, so a library method and a syntax feature are
 *  measured on ONE scale. */
export function eraOf(libFile: string): number | null {
  const m = /^lib\.(es\d+|es5|esnext)\b/.exec(libFile);
  if (!m) return null;
  if (m[1] === 'es5') return 2009;
  if (m[1] === 'esnext') return null;   // no year to give; excluded on purpose
  const n = Number(m[1].slice(2));
  return Number.isFinite(n) ? n : null;
}

export interface LibMember { proto: string; method: string; since: number; file: string }

/** every member of the eight prototypes, with the EARLIEST lib file that
 *  declares it — the year it became available. */
export function scanLib(libDir: string): LibMember[] {
  const files = fs.readdirSync(libDir)
    .filter((f) => /^lib\.[a-z0-9.]*\.d\.ts$/.test(f) && eraOf(f) !== null)
    .sort();
  const earliest = new Map<string, LibMember>();
  for (const f of files) {
    const since = eraOf(f)!;
    const src = ts.createSourceFile(f, fs.readFileSync(path.join(libDir, f), 'utf8'),
                                    ts.ScriptTarget.Latest, true);
    for (const st of src.statements) {
      if (!ts.isInterfaceDeclaration(st)) continue;
      const proto = PROTOTYPES.get(st.name.text);
      if (!proto) continue;
      for (const mem of st.members) {
        if (!ts.isMethodSignature(mem) && !ts.isPropertySignature(mem)) continue;
        // A COMPUTED NAME IS A SYMBOL, and a symbol-keyed member is not a name
        // a member expression in this corpus can spell. `selects[flow]` answers
        // a KEY, so the surface is keyed by names too.
        if (!mem.name || !ts.isIdentifier(mem.name)) continue;
        const key = `${proto}.${mem.name.text}`;
        const prev = earliest.get(key);
        if (!prev || since < prev.since) {
          earliest.set(key, { proto, method: mem.name.text, since, file: f });
        }
      }
    }
  }
  return [...earliest.values()]
    .sort((a, b) => (a.proto === b.proto ? (a.method < b.method ? -1 : 1) : (a.proto < b.proto ? -1 : 1)));
}

/** the pack, as text. Deterministic: sorted, and every row carries its source. */
export function emit(members: LibMember[]): string {
  const head = [
    '-- js-lib-surface.rofl — GENERATED by scanners/ts_lib.ts. Do not hand-edit;',
    '-- test/js-lib-surface.test.ts regenerates it and compares, so a hand edit',
    '-- shows up as a failing test rather than as a silent divergence.',
    '--',
    '-- `lib_member(Prototype, Method, Year)` — the name exists on that prototype',
    '-- from that year, read from TypeScript`s own lib.es*.d.ts declarations. The',
    '-- year is the earliest lib file that declares it, which is the record',
    '-- TypeScript keeps of when each method landed.',
    'edb(lib_member).',
    '',
  ];
  // THE METHOD IS A QUOTED STRING AND THE PROTOTYPE IS AN ATOM, which is not a
  // style choice: `stdlib_member[audit]` gets its key from `selects[flow]`,
  // which reads an `ast_attr` VALUE, and every attribute value the scanner emits
  // is quoted. The first draft wrote both as atoms, the join produced ZERO rows
  // out of six, and `stdlib_unattributed[audit]` reported all six — the audit
  // written to notice a wrong prototype noticing a wrong TERM TYPE instead,
  // which is the same class of mistake one level down.
  const rows = members.map((m) => `lib_member(${m.proto}, ${JSON.stringify(m.method)}, ${m.since}).`);
  return head.concat(rows).join('\n') + '\n';
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
  const out = emit(scanLib(path.join(root, 'node_modules', 'typescript', 'lib')));
  const dest = path.join(root, 'facts', 'js-lib-surface.rofl');
  fs.writeFileSync(dest, out);
  console.log(`${dest}: ${out.split('\n').filter((l) => l.startsWith('lib_member')).length} members`);
}
