// bridge.ts — THE FAMILY'S BOOK EXTENDS THE WORLD, generated. spat.rofl §14
// declares, per edb relation, how a fact of the book [hh] reaches main:
// `key_of(R, N)` (the first N arguments identify a fact), `not_extended(R, Why)`,
// `extends_unless(R, I, V)`, `speaks_for(R, I)`, `key_owned(R, G)`. This file
// turns those lines into `bridge.rofl` — one block per relation, the arity
// read off the rules' own use of it — so nobody writes forty bridges by hand
// and a new edb line without a decision stops the generator. The demo
// (examples/spat_places) regenerates and refuses a stale file.
//
//   node --experimental-strip-types examples/spat/bridge.ts           write examples/spat/bridge.rofl
//   node --experimental-strip-types examples/spat/bridge.ts --check   exit 1 if the file is not what this would write

import * as fs from 'node:fs';
import * as path from 'node:path';
import { parseProgram } from '../../src/parser.ts';
import type { Clause, Lit, Term } from '../../src/unify.ts';

const HERE = path.dirname(new URL(import.meta.url).pathname);
export const BRIDGE = path.join(HERE, 'bridge.rofl');
const PROGRAM = ['spat.rofl', 'access.rofl', 'volumes.rofl'];
// the arity of a relation no rule reads (`week/1`, the CLI's) is read off the shipped example
const ARITY_FROM = [...PROGRAM, 'week.example.rofl'];

const atom = (t: Term | undefined): string => (t?.k === 'a' ? t.name : t?.k === 'i' ? String(t.v) : '');
const facts = (cs: Clause[], rel: string): Term[][] => cs.filter((c) => c.body.length === 0 && c.head.rel === rel).map((c) => c.head.args);

/** Every literal of a program, heads and bodies. */
function literals(cs: Clause[]): Lit[] {
  const out: Lit[] = [];
  for (const c of cs) { out.push(c.head); for (const b of c.body) if (b.t !== 'bi') out.push(b.lit); }
  return out;
}

const vars = (n: number): string[] => Array.from({ length: n }, (_, i) => `X${i + 1}`);
/** `$cons(X1, $cons(X2, _))` — the first `k` elements of the kernel's argument list, the rest unread. */
const consOf = (k: number): string => (k === 0 ? '_' : vars(k).reduceRight((rest, v) => `$cons(${v}, ${rest})`, '_'));

/** The text of bridge.rofl for the declarations in spat.rofl — or in `spatText`, for a demo to plant a missing decision. */
export function render(spatText?: string): string {
  const cs = ARITY_FROM.flatMap((f) => parseProgram(fs.readFileSync(path.join(HERE, f), 'utf8')));
  const spat = parseProgram(spatText ?? fs.readFileSync(path.join(HERE, 'spat.rofl'), 'utf8'));
  const edb = facts(spat, 'edb').map((a) => atom(a[0]));
  const keyOf = new Map(facts(spat, 'key_of').map((a) => [atom(a[0]), Number(atom(a[1]))]));
  const notExt = new Map(facts(spat, 'not_extended').map((a) => [atom(a[0]), atom(a[1])]));
  const unless = facts(spat, 'extends_unless').map((a) => ({ rel: atom(a[0]), i: Number(atom(a[1])), v: atom(a[2]) }));
  const speaks = facts(spat, 'speaks_for').map((a) => ({ rel: atom(a[0]), i: Number(atom(a[1])) }));
  const reserved = facts(spat, 'key_owned').map((a) => ({ rel: atom(a[0]), g: atom(a[1]) }));
  const arities = new Map<string, Set<number>>();
  for (const l of literals(cs)) { if (!arities.has(l.rel)) arities.set(l.rel, new Set()); arities.get(l.rel)!.add(l.args.length); }
  const out = [
    '-- bridge.rofl — GENERATED by examples/spat/bridge.ts from spat.rofl §14. Do not edit.',
    '-- A fact of the family\'s book [hh] on an edb relation is one more line of the',
    '-- world — added, never overriding: `world_R` is what the world book asserted',
    '-- (the kernel\'s trail), a book fact whose key the world has with another',
    '-- value is `overrides[audit]` and ignored, one the book may not state is',
    '-- `withheld[audit]`. Both are audits, both are read by `spat rule add`.',
    '',
  ];
  for (const rel of edb) {
    const why = notExt.get(rel);
    if (why !== undefined) { out.push(`-- ${rel}: not extended (${why})`); continue; }
    const key = keyOf.get(rel);
    if (key === undefined) throw new Error(`spat.rofl: edb(${rel}) has neither key_of nor not_extended — decide it in §14`);
    const ns = [...(arities.get(rel) ?? [])].sort();
    if (ns.length === 0) throw new Error(`spat.rofl: edb(${rel}) is used by no rule — its arity is unknown`);
    for (const n of ns) {
      if (key > n) throw new Error(`spat.rofl: key_of(${rel}, ${key}) but ${rel}/${n}`);
      const xs = vars(n); const args = xs.join(', '); const kargs = xs.slice(0, key).join(', ');
      const guards: string[] = []; const held: string[] = [];
      if (key < n) {
        out.push(`-- ${rel}/${n}, key ${key}`);
        out.push(`world_${rel}(${kargs}) :- asserted_by($fact(${rel}, main, ${consOf(key)}), _, _).`);
        guards.push(`not world_${rel}(${kargs})`);
      } else out.push(`-- ${rel}/${n}, a set`);
      for (const u of unless.filter((x) => x.rel === rel)) {
        guards.push(`X${u.i} != ${u.v}`);
        held.push(`withheld[audit](${rel}, k(${xs.map((x, j) => (j === u.i - 1 ? u.v : x)).join(', ')})) :- ${rel}[hh](${xs.map((x, j) => (j === u.i - 1 ? u.v : x)).join(', ')}).`);
      }
      for (const s of speaks.filter((x) => x.rel === rel)) {
        guards.push(`not person(X${s.i}, helper)`);
        held.push(`withheld[audit](${rel}, k(${args})) :- ${rel}[hh](${args}), person(X${s.i}, helper).`);
      }
      for (const r of reserved.filter((x) => x.rel === rel)) {
        const gn = [...(arities.get(r.g) ?? [])][0] ?? 1;
        const gargs = ['X1', ...Array.from({ length: gn - 1 }, () => '_')].join(', ');
        guards.push(`not ${r.g}(${gargs})`);
        held.push(`withheld[audit](${rel}, k(${args})) :- ${rel}[hh](${args}), ${r.g}(${gargs}).`);
      }
      out.push(`${rel}(${args}) :- ${rel}[hh](${args})${guards.map((g) => `, ${g}`).join('')}.`);
      // a singleton's override names the fact itself (its key is empty)
      if (key < n) out.push(`overrides[audit](${rel}, k(${key === 0 ? args : kargs})) :- ${rel}[hh](${args}), world_${rel}(${kargs}), not ${rel}(${args}).`);
      out.push(...held);
    }
  }
  return out.join('\n') + '\n';
}

if (process.argv[1] && path.resolve(process.argv[1]) === new URL(import.meta.url).pathname) {
  const text = render();
  if (process.argv.includes('--check')) {
    const now = fs.existsSync(BRIDGE) ? fs.readFileSync(BRIDGE, 'utf8') : '';
    if (now !== text) { console.log(`${path.relative(process.cwd(), BRIDGE)} is stale — run examples/spat/bridge.ts`); process.exit(1); }
    console.log(`${path.relative(process.cwd(), BRIDGE)} is what spat.rofl §14 says`);
  } else { fs.writeFileSync(BRIDGE, text); console.log(`${path.relative(process.cwd(), BRIDGE)}: ${text.split('\n').length} lines`); }
}
