// scripts/agg_prose.ts — THE PROSE THE AGGREGATES PROGRAMME FALSIFIES, AS FACTS.
//
// facts/agg.rofl owns `contradiction_site(w_agg_reconcile_docs, Path, What)`
// rows: places that said ROFL has no aggregation. A world cannot read a
// document, so this writes down, for each owned path, every block of it that
// still says so (`prose_claim`) and which of those point at docs/aggregates.md
// (`prose_pointer`: the block itself, or an `> **Amended` note straight
// after it). The world `agg_prose` (examples/checks/agg-prose-check.rofl) raises
// `prose_stale` for a claim with no pointer, and `npm test` regenerates this
// pack and compares, so the photograph cannot go stale
// (f_a_golden_over_a_generated_census_pins_the_photograph_against_itself).
//
//   node --experimental-strip-types scripts/agg_prose.ts [--write | --check]
//
// A block is keyed by its first 60 characters, not its line, so an edit
// elsewhere in the file does not stale the pack. A block is a run of lines with no blank line; a fact (`rel(...)` at a
// line start) ends its block, so a comment and the fact under it are one block.
import * as fs from 'node:fs';
import * as path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
export const PACK = 'examples/checks/agg-prose-census.rofl';
const ITEM = 'w_agg_reconcile_docs';
const POINTER = /docs\/aggregates\.md/;
const STALE: RegExp[] = [
  /\bno aggregation\b/i,
  /\baggregation,? GPU\b/i,
  /\baggregation\b[^.]{0,40}\bout of scope\b/i,
  /\bone aggregate, in a rule body\b/i,
];
const FACT = /^[a-z_]+(\[[a-z_]+\])?\(/;

type Block = { line: number; text: string; first: string };

export function blocks(source: string): Block[] {
  const out: Block[] = [];
  let cur: { line: number; rows: string[] } | null = null;
  let prev = '';
  const close = (): void => {
    if (cur) out.push({ line: cur.line, text: cur.rows.map((r) => r.replace(/^\s*(--|>|#)\s?/, '').trim()).join(' ').replace(/\s+/g, ' '), first: cur.rows[0] });
    cur = null;
  };
  source.split('\n').forEach((l, i) => {
    if (l.trim() === '') { close(); prev = ''; return; }
    if (cur && FACT.test(prev) && (FACT.test(l) || /^\s*--/.test(l))) close();
    if (!cur) cur = { line: i + 1, rows: [] };
    cur.rows.push(l);
    prev = l;
  });
  close();
  return out;
}

/** The paths `ITEM` owns, as facts/agg.rofl writes them. */
export function ownedPaths(): string[] {
  const text = fs.readFileSync(path.join(ROOT, 'facts/agg.rofl'), 'utf8');
  const re = new RegExp(`^contradiction_site\\(${ITEM}, "([^"]+)"`, 'gm');
  return [...new Set([...text.matchAll(re)].map((m) => m[1]))].sort();
}

export function pack(): string {
  const q = (s: string): string => JSON.stringify(s);
  const L = [
    `-- ${PACK} — GENERATED by \`node --experimental-strip-types scripts/agg_prose.ts --write\`.`,
    `-- The blocks of the paths ${ITEM} owns that still say there is no aggregation, and`,
    '-- which of them point at docs/aggregates.md; `npm test` fails when this is stale.',
    '',
    'edb(prose_site).', 'edb(prose_claim).', 'edb(prose_pointer).', '',
  ];
  for (const p of ownedPaths()) {
    L.push(`prose_site(${q(p)}).`);
    const bs = blocks(fs.readFileSync(path.join(ROOT, p), 'utf8'));
    bs.forEach((b, i) => {
      if (!STALE.some((r) => r.test(b.text))) return;
      const key = q(b.text.slice(0, 60));
      L.push(`prose_claim(${q(p)}, ${key}).`);
      const next = bs[i + 1];
      if (POINTER.test(b.text) || (next && /^>\s*\*\*Amended/.test(next.first) && POINTER.test(next.text))) {
        L.push(`prose_pointer(${q(p)}, ${key}).`);
      }
    });
  }
  return L.join('\n') + '\n';
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === path.resolve(import.meta.filename);
if (isMain) {
  const fresh = pack(), file = path.join(ROOT, PACK);
  const held = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
  if (process.argv.includes('--write')) {
    if (held !== fresh) fs.writeFileSync(file, fresh);
    console.log(`  ${held === fresh ? 'ok   ' : 'wrote'} ${PACK}`);
    process.exit(0);
  }
  if (held === fresh) { console.log(`  ok    ${PACK}`); process.exit(0); }
  console.log(`  STALE ${PACK} — run \`node --experimental-strip-types scripts/agg_prose.ts --write\``);
  process.exit(1);
}
