// scripts/build_kernel_dense.ts — compile the kernel's own programs.
//
// policy.rofl and safety.rofl are the SOURCE. This renders them into the dense
// form src/dense.ts reads and writes src/kernel-dense.ts, so that the kernel
// never parses the language it is written in just to run its own policy.
//
// The correspondence is a gate, not a promise: `--check` re-renders from the
// .rofl files and compares, so a source edit that is not rebuilt goes red
// rather than silently shipping the old program. It said
// `test/kernel-policy-program.test.ts` until 2026-09-18, and that file went
// with `test/` on 2026-09-11 -- seven days in which the header promised a gate
// that did not exist, which is the class this tree has recorded four times.
//
// The same two programs are the ROOT of the Rust crate, which cannot reach
// this tree once it is packaged: `rust/rofl/src/kernel/*.dense` is the copy it
// carries, written here and checked here.
//
//   npm run build:dense
//   npm run build:dense -- --check

import * as fs from 'node:fs';
import * as path from 'node:path';
import { parseProgram } from '../src/parser.ts';
import { dense } from '../examples/ring1/dense.ts';

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');

export function renderDense(file: string): string {
  return dense(parseProgram(fs.readFileSync(path.join(ROOT, file), 'utf8')));
}

const isMain = process.argv[1] && path.resolve(process.argv[1]).includes('build_kernel_dense');
if (isMain) {
  const policy = renderDense('policy.rofl');
  const safety = renderDense('safety.rofl');
  const esc = (s: string) => s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
  const out = `// src/kernel-dense.ts — GENERATED by scripts/build_kernel_dense.ts.
//
// The kernel's two programs, compiled into the dense form src/dense.ts reads.
// policy.rofl and safety.rofl are the source; regenerate with
// \`npm run build:dense\` and test/kernel-policy-program.test.ts checks that you
// did. Nothing here is written by hand.
//
// WHY THIS FILE EXISTS: until 2026-09-06 the kernel carried these as source
// text and called \`parseProgram\` on them the first time any store with rules
// was evaluated -- which made the 262-line surface parser load-bearing for the
// evaluator itself. Measured: a host that loads only dense facts entered 195
// of the parser's 262 lines, and 168 of those were this parse.

export const POLICY_DENSE = \`${esc(policy)}\`;

export const SAFETY_DENSE = \`${esc(safety)}\`;
`;
  const artefacts: [string, string][] = [
    [path.join('src', 'kernel-dense.ts'), out],
    [path.join('rust', 'rofl', 'src', 'kernel', 'policy.dense'), policy],
    [path.join('rust', 'rofl', 'src', 'kernel', 'safety.dense'), safety],
  ];

  if (process.argv.includes('--check')) {
    const stale = artefacts.filter(([f, want]) => {
      const at = path.join(ROOT, f);
      return !fs.existsSync(at) || fs.readFileSync(at, 'utf8') !== want;
    });
    for (const [f] of stale) console.error(`STALE ${f}`);
    if (stale.length) {
      console.error('regenerate with: npm run build:dense');
      process.exit(1);
    }
    console.error(`kernel programs current: policy ${policy.length} bytes, safety ${safety.length} bytes`);
  } else {
    for (const [f, text] of artefacts) {
      const at = path.join(ROOT, f);
      fs.mkdirSync(path.dirname(at), { recursive: true });
      fs.writeFileSync(at, text);
    }
    console.error(`${artefacts.length} artefacts: policy ${policy.length} bytes, safety ${safety.length} bytes`);
  }
}
