// scripts/build_kernel_dense.ts — compile the kernel's own programs.
//
// policy.rofl and safety.rofl are the SOURCE. This renders them into the dense
// form src/dense.ts reads and writes src/kernel-dense.ts, so that the kernel
// never parses the language it is written in just to run its own policy.
//
// The correspondence is a gate, not a promise: test/kernel-policy-program.test
// re-renders from the .rofl files and compares, so a source edit that is not
// rebuilt goes red rather than silently shipping the old program.
//
//   npm run build:dense

import * as fs from 'node:fs';
import * as path from 'node:path';
import { parseProgram } from '../src/parser.ts';
import { dense } from '../examples/ring1/dense.ts';

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');

export function renderDense(file: string): string {
  return dense(parseProgram(fs.readFileSync(path.join(ROOT, file), 'utf8')));
}

const isMain = process.argv[1] && path.resolve(process.argv[1]).includes('build_kernel_dense');
if (isMain) {
  const policy = renderDense('policy.rofl');
  const safety = renderDense('safety.rofl');
  const esc = (s: string) => s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
  const out = `// src/kernel-dense.ts — GENERATED by scripts/build_kernel_dense.ts.
//
// The kernel's two programs, compiled into the dense form src/dense.ts reads.
// policy.rofl and safety.rofl are the source; regenerate with
// \`npm run build:dense\` and test/kernel-policy-program.test.ts checks that you
// did. Nothing here is written by hand.
//
// WHY THIS FILE EXISTS: until 2026-09-06 the kernel carried these as source
// text and called \`parseProgram\` on them the first time any store with rules
// was evaluated -- which made the 262-line surface parser load-bearing for the
// evaluator itself. Measured: a host that loads only dense facts entered 195
// of the parser's 262 lines, and 168 of those were this parse.

export const POLICY_DENSE = \`${esc(policy)}\`;

export const SAFETY_DENSE = \`${esc(safety)}\`;
`;
  fs.writeFileSync(path.join(ROOT, 'src', 'kernel-dense.ts'), out);
  console.error(`src/kernel-dense.ts: policy ${policy.length} bytes, safety ${safety.length} bytes`);
}
