// The facts of the side-effect question's corpus (examples/vscode/side-effects.rofl), as the notebook host makes them.
//   fixture [BASE SUB OUT]          examples/vscode/mini -> examples/checks/vscode-mini-facts.rofl, or BASE/SUB -> OUT
//   corpus ROOT OUT [N...]          vscode's subset S (src/vs/{base,platform,code,server} and extensions/, no tests), in
//                                   that order and by path within it; OUT/files.lst, and OUT/facts-<N>.rofl holding the
//                                   files after the previous size up to N (the last is every file), so a size is its
//                                   prefix of chunks; the files no parser read are printed and in OUT/parse-errors.lst
import * as fs from 'node:fs';
import * as path from 'node:path';
import { codeFacts } from '../playground/host.ts';

const ROOT = new URL('..', import.meta.url).pathname;
const CODE = /\.(js|ts|tsx|mjs|cjs|jsx|mts|cts)$/;
const SKIP_DIR = new Set(['node_modules', '.git', 'dist', 'build', 'out', '.yarn', 'vendor', 'third_party', 'coverage', 'generated', '__generated__', 'typings', 'docs', '.vscode-test']);
const TEST_DIR = new Set(['test', 'tests', '__tests__', '__mocks__', 'fixtures', 'fixture', '__fixtures__', 'e2e', 'testdata', 'test-fixtures', 'mocks', 'smoke', 'integration', 'benchmark', 'benchmarks', 'examples', 'example', 'playground']);
const NOT_SOURCE = /\.(test|spec|e2e|e2e-spec|stories)\.[a-z]+$|\.d\.[mc]?ts$|\.min\.js$|\.generated\./;
const SUBSET = ['src/vs/base', 'src/vs/platform', 'src/vs/code', 'src/vs/server', 'extensions'];

function walk(root: string, dir: string, out: string[]): void {
  for (const e of fs.readdirSync(path.join(root, dir), { withFileTypes: true }).sort((a, b) => a.name < b.name ? -1 : 1)) {
    const rel = `${dir}/${e.name}`;
    if (e.isDirectory()) { if (!SKIP_DIR.has(e.name) && !TEST_DIR.has(e.name)) walk(root, rel, out); }
    else if (CODE.test(e.name) && !NOT_SOURCE.test(e.name)) out.push(rel);
  }
}

function factsOf(root: string, files: string[], seen: Set<string>): { text: string; errors: [string, string][] } {
  const { facts, parseErrors, host } = codeFacts(Object.fromEntries(files.map((f) => [f, fs.readFileSync(path.join(root, f), 'utf8')])));
  const fresh = host.filter((h) => !seen.has(h) && seen.add(h));
  return { text: facts.join('\n') + '\n' + fresh.join('\n') + '\n', errors: Object.entries(parseErrors) };
}

const [mode, ...rest] = process.argv.slice(2);
if (mode === 'fixture') {
  const [base, sub, out] = rest.length ? rest : ['examples/vscode', 'mini', 'examples/checks/vscode-mini-facts.rofl'];
  const dir = path.join(ROOT, base);
  const files: string[] = [];
  walk(dir, sub, files);
  const { text, errors } = factsOf(dir, files, new Set());
  if (errors.length) throw new Error(`the fixture does not parse: ${JSON.stringify(errors)}`);
  const how = rest.length ? ` ${rest.join(' ')}` : '';
  fs.writeFileSync(path.join(ROOT, out),
    `-- GENERATED by \`node --experimental-strip-types scripts/vscode_corpus.ts fixture${how}\`: the facts of ${base}/${sub} as the notebook\n-- host gives them (scanners/js_ast.ts and the host's path and string facts). Regenerate when the scanner moves.\n${text}`);
  console.log(`${files.length} files`);
} else if (mode === 'corpus') {
  const [root, out, ...sizes] = rest;
  const files: string[] = [];
  for (const d of SUBSET) walk(root, d, files);
  fs.mkdirSync(out, { recursive: true });
  fs.writeFileSync(path.join(out, 'files.lst'), files.join('\n') + '\n');
  const cuts = [...sizes.map(Number).filter((n) => n < files.length), files.length];
  const seen = new Set<string>(), errors: [string, string][] = [];
  let from = 0;
  for (const to of cuts) {
    const target = path.join(out, `facts-${to}.rofl`);
    fs.writeFileSync(target, '');
    const t0 = performance.now();
    for (let i = from; i < to; i += 100) {
      const r = factsOf(root, files.slice(i, Math.min(i + 100, to)), seen);
      fs.appendFileSync(target, r.text);
      errors.push(...r.errors);
    }
    console.log(`${to} files: ${target}, ${(fs.statSync(target).size / 1e6).toFixed(0)} MB, ${Math.round(performance.now() - t0)} ms`);
    from = to;
  }
  fs.writeFileSync(path.join(out, 'parse-errors.lst'), errors.map(([f, e]) => `${f}\t${e}`).join('\n') + '\n');
  console.log(`${files.length} files, ${errors.length} not parsed`);
  for (const [f, e] of errors) console.log(`  ${f}: ${e}`);
} else {
  console.error('usage: vscode_corpus.ts fixture | corpus ROOT OUT [N...]');
  process.exit(64);
}
