apiVersion: v1
kind: Service
metadata:
  name: billing-svc
spec:
  selector:
    app: billing
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing
spec:
  template:
    metadata:
      labels:
        app: billing
    spec:
      containers:
        - name: app
          image: billing-go:1.0
          ports:
            - containerPort: 8081
