// src/kernel-dense.ts — GENERATED by scripts/build_kernel_dense.ts.
//
// The kernel's two programs and its shrug vocabulary (shrug.rofl), compiled into the dense form src/dense.ts reads.
// policy.rofl and safety.rofl are the source; regenerate with
// `npm run build:dense` and test/kernel-policy-program.test.ts checks that you
// did. Nothing here is written by hand.
//
// WHY THIS FILE EXISTS: until 2026-09-06 the kernel carried these as source
// text and called `parseProgram` on them the first time any store with rules
// was evaluated -- which made the 262-line surface parser load-bearing for the
// evaluator itself. Measured: a host that loads only dense facts entered 195
// of the parser's 262 lines, and 168 of those were this parse.

export const POLICY_DENSE = `r(r1, l(rule_reads, [v("A"), v("B")]), [l(concludes, [v("R"), v("A")]), l(premise_pos, [v("R"), v("B")])]).
r(r2, l(rule_reads, [v("A"), v("B")]), [l(concludes, [v("R"), v("A")]), l(premise_neg, [v("R"), v("B")])]).
r(r3, l(rule_reads, [v("A"), v("B")]), [l(concludes, [v("R"), v("A")]), l(premise_agg, [v("R"), v("B")])]).
r(r4, l(rule_relation, [v("A")]), [l(concludes, [v("R"), v("A")])]).
r(r5, l(rule_relation, [v("B")]), [l(rule_reads, [v("A"), v("B")])]).
r(r6, l(cone, [v("A"), v("A")]), [l(rule_relation, [v("A")])]).
r(r7, l(cone, [v("A"), v("C")]), [l(cone, [v("A"), v("B")]), l(rule_reads, [v("B"), v("C")])]).
edb(opaque_seed).
r(r8, l(opaque_closed, [v("A")]), [l(opaque_seed, [v("A")])]).
r(r9, l(opaque_closed, [v("A")]), [l(rule_reads, [v("A"), v("B")]), l(opaque_closed, [v("B")])]).
`;

export const SAFETY_DENSE = `edb(premise_var).
edb(slot_arity).
r(r1, l(slot, [v("R"), v("K"), left]), [l(premise_lit, [v("R"), v("K"), f("$builtin", [v("_$0"), v("_$1")])])]).
r(r2, l(slot, [v("R"), v("K"), right]), [l(premise_lit, [v("R"), v("K"), f("$builtin", [v("_$0"), v("_$1")])])]).
r(r3, l(binds_at, [v("R"), v("K"), v("V")]), [l(premise_var, [v("R"), v("K"), pos, v("_$0"), v("V")])]).
r(r4, l(binds_at, [v("R"), v("K"), v("V")]), [l(premise_lit, [v("R"), v("K"), f("$builtin", [s("is"), v("_$0")])]), l(ground, [v("R"), v("K"), right]), l(premise_var, [v("R"), v("K"), left, v("_$1"), v("V")])]).
r(r5, l(binds_at, [v("R"), v("K"), v("V")]), [l(premise_lit, [v("R"), v("K"), f("$builtin", [s("in"), v("_$0")])]), l(ground, [v("R"), v("K"), right]), l(premise_var, [v("R"), v("K"), left, v("_$1"), v("V")])]).
r(r6, l(binds_at, [v("R"), v("K"), v("V")]), [l(premise_lit, [v("R"), v("K"), f("$builtin", [s("="), v("_$0")])]), l(ground, [v("R"), v("K"), left]), l(premise_var, [v("R"), v("K"), right, v("_$1"), v("V")])]).
r(r7, l(binds_at, [v("R"), v("K"), v("V")]), [l(premise_lit, [v("R"), v("K"), f("$builtin", [s("="), v("_$0")])]), l(ground, [v("R"), v("K"), right]), l(premise_var, [v("R"), v("K"), left, v("_$1"), v("V")])]).
r(r8, l(bound_before, [v("R"), v("K"), v("V")]), [l(binds_at, [v("R"), v("J"), v("V")]), b("is", v("K"), f("+", [v("J"), 1])), l(has_premise, [v("R"), v("K")])]).
r(r9, l(bound_before, [v("R"), v("K"), v("V")]), [l(bound_before, [v("R"), v("J"), v("V")]), b("is", v("K"), f("+", [v("J"), 1])), l(has_premise, [v("R"), v("K")])]).
r(r10, l(ground_upto, [v("R"), v("K"), v("S"), 0]), [l(slot, [v("R"), v("K"), v("S")])]).
r(r11, l(ground_upto, [v("R"), v("K"), v("S"), v("I")]), [l(ground_upto, [v("R"), v("K"), v("S"), v("J")]), b("is", v("I"), f("+", [v("J"), 1])), l(premise_var, [v("R"), v("K"), v("S"), v("I"), v("V")]), l(bound_before, [v("R"), v("K"), v("V")])]).
r(r12, l(ground, [v("R"), v("K"), v("S")]), [l(ground_upto, [v("R"), v("K"), v("S"), v("N")]), l(slot_arity, [v("R"), v("K"), v("S"), v("N")])]).
r(r13, l(analysed, [v("R")]), [l(slot_arity, [v("R"), 0, head, v("_$0")])]).
r(r14, l(binds, [v("R"), v("V")]), [l(binds_at, [v("R"), v("_$0"), v("V")])]).
eq_or_is(s("=")).
eq_or_is(s("is")).
eq_or_is(s("in")).
r(r15, l(op_used, [v("Op")]), [l(premise_lit, [v("_$0"), v("_$1"), f("$builtin", [v("Op"), v("_$2")])])]).
r(r16, l(cmp_op, [v("Op")]), [l(op_used, [v("Op")]), n(l(eq_or_is, [v("Op")]))]).
r(r17, l(unsafe_rule, [v("R")]), [l(premise_var, [v("R"), 0, head, v("_$0"), v("V")]), n(l(binds, [v("R"), v("V")]))]).
r(r18, l(unsafe_rule, [v("R")]), [l(analysed, [v("R")]), l(premise_lit, [v("R"), v("K"), f("$builtin", [s("is"), v("_$0")])]), n(l(ground, [v("R"), v("K"), right]))]).
r(r19, l(unsafe_rule, [v("R")]), [l(analysed, [v("R")]), l(premise_lit, [v("R"), v("K"), f("$builtin", [s("in"), v("_$0")])]), n(l(ground, [v("R"), v("K"), right]))]).
r(r20, l(unsafe_rule, [v("R")]), [l(analysed, [v("R")]), l(premise_lit, [v("R"), v("K"), f("$builtin", [s("="), v("_$0")])]), n(l(ground, [v("R"), v("K"), left])), n(l(ground, [v("R"), v("K"), right]))]).
r(r21, l(unsafe_rule, [v("R")]), [l(analysed, [v("R")]), l(premise_lit, [v("R"), v("K"), f("$builtin", [v("Op"), v("_$0")])]), l(cmp_op, [v("Op")]), n(l(ground, [v("R"), v("K"), left]))]).
r(r22, l(unsafe_rule, [v("R")]), [l(analysed, [v("R")]), l(premise_lit, [v("R"), v("K"), f("$builtin", [v("Op"), v("_$0")])]), l(cmp_op, [v("Op")]), n(l(ground, [v("R"), v("K"), right]))]).
r(r23, l(blocked_head, [v("R")]), [l(analysed, [v("R")]), l(concludes, [v("R"), v("Rel")]), l(reserved, [v("Rel")])]).
r(r24, l(executable, [v("R")]), [l(analysed, [v("R")]), n(l(blocked_head, [v("R")]))]).
r(r25, l(has_neg_rule, [v("R")]), [l(analysed, [v("R")]), l(premise_neg, [v("R"), v("_$0")])]).
r(r26, l(has_agg_rule, [v("R")]), [l(analysed, [v("R")]), l(premise_agg, [v("R"), v("_$0")])]).
r(r27, l(mono_rule, [v("R")]), [l(executable, [v("R")]), n(l(has_neg_rule, [v("R")])), n(l(has_agg_rule, [v("R")])), n(l(unsafe_rule, [v("R")]))]).
stratum_cone(stratum).
r(r28, l(stratum_cone, [v("Rel")]), [l(concludes, [v("R"), v("Rel")]), l(mono_rule, [v("R")]), l(premise_pos, [v("R"), v("Q")]), l(stratum_cone, [v("Q")])]).
r(r29, l(late_rule, [v("R")]), [l(concludes, [v("R"), v("Rel")]), l(mono_rule, [v("R")]), l(stratum_cone, [v("Rel")])]).
r(r30, l(demand_rel, [v("Rel")]), [l(concludes, [v("R"), v("Rel")]), l(conclusion_tense, [v("R"), now]), l(executable, [v("R")]), l(unsafe_rule, [v("R")])]).
r(r31, l(demand_rel, [v("Rel")]), [l(concludes, [v("R"), v("Rel")]), l(conclusion_tense, [v("R"), now]), l(executable, [v("R")]), l(premise_pos, [v("R"), v("Q")]), l(demand_rel, [v("Q")])]).
r(r32, l(trigger_of, [v("P"), v("P")]), [l(analysed, [v("R")]), l(premise_pos, [v("R"), v("P")])]).
r(r33, l(trigger_of, [v("P"), v("X")]), [l(demand_rel, [v("P")]), l(concludes, [v("R"), v("P")]), l(conclusion_tense, [v("R"), now]), l(executable, [v("R")]), l(premise_pos, [v("R"), v("Q")]), l(trigger_of, [v("Q"), v("X")])]).
r(r34, l(neg_relation, [v("A")]), [l(analysed, [v("R")]), l(premise_neg, [v("R"), v("A")])]).
r(r35, l(provenance_reader, [v("R")]), [l(analysed, [v("R")]), l(premise_pos, [v("R"), derived_by])]).
r(r36, l(provenance_reader, [v("R")]), [l(analysed, [v("R")]), l(premise_neg, [v("R"), derived_by])]).
r(r37, l(provenance_reader, [v("R")]), [l(analysed, [v("R")]), l(premise_agg, [v("R"), derived_by])]).
edb(agg_inner).
r(r38, l(binds_at, [v("R"), v("K"), v("V")]), [l(premise_var, [v("R"), v("K"), agg, v("_$0"), v("V")])]).
r(r39, l(binds_at, [v("R"), v("K"), v("V")]), [l(premise_var, [v("R"), v("K"), agg_res, v("_$0"), v("V")])]).
r(r40, l(binds_at, [v("I"), 0, v("V")]), [l(agg_inner, [v("R"), v("K"), v("I")]), l(bound_before, [v("R"), v("K"), v("V")])]).
r(r41, l(agg_op, [v("R"), v("K"), v("Op")]), [l(premise_lit, [v("R"), v("K"), f("$agg", [v("Op"), v("_$0"), v("_$1"), v("_$2"), v("_$3")])])]).
r(r42, l(agg_keyed, [v("R"), v("K")]), [l(premise_lit, [v("R"), v("K"), f("$agg", [v("_$0"), v("_$1"), v("_$2"), f("$cons", [v("_$3"), v("_$4")]), v("_$5")])])]).
r(r43, l(agg_one_value, [v("R"), v("K")]), [l(premise_lit, [v("R"), v("K"), f("$agg", [v("_$0"), v("_$1"), f("$cons", [v("_$2"), $nil]), v("_$3"), v("_$4")])])]).
r(r44, l(agg_no_value, [v("R"), v("K")]), [l(premise_lit, [v("R"), v("K"), f("$agg", [v("_$0"), v("_$1"), $nil, v("_$2"), v("_$3")])])]).
needs_key(sum).
one_value_op(sum).
one_value_op(min).
one_value_op(max).
one_value_op(or).
one_value_op(and).
idempotent_op(min).
idempotent_op(max).
idempotent_op(or).
idempotent_op(and).
idempotent_op(union).
idempotent_op(hull).
idempotent_op(bitor).
live_kernel_rel(derived_by).
live_kernel_rel(hole).
live_kernel_rel(agg_cell).
live_kernel_rel(agg_member).
live_kernel_rel(agg_member_prem).
live_kernel_rel(agg_sealed).
live_kernel_rel(lattice_member).
live_kernel_rel(lattice_member_prem).
live_kernel_rel(dominated_by).
r(r45, l(agg_refused, [v("R"), sum_needs_key]), [l(agg_op, [v("R"), v("K"), v("Op")]), l(needs_key, [v("Op")]), n(l(agg_keyed, [v("R"), v("K")]))]).
r(r46, l(agg_refused, [v("R"), key_on_count]), [l(agg_op, [v("R"), v("K"), count]), l(agg_keyed, [v("R"), v("K")])]).
r(r47, l(agg_refused, [v("R"), key_on_idempotent]), [l(agg_op, [v("R"), v("K"), v("Op")]), l(idempotent_op, [v("Op")]), l(agg_keyed, [v("R"), v("K")])]).
r(r48, l(agg_refused, [v("R"), one_value]), [l(agg_op, [v("R"), v("K"), v("Op")]), l(one_value_op, [v("Op")]), n(l(agg_one_value, [v("R"), v("K")]))]).
r(r49, l(agg_refused, [v("R"), count_needs_a_term]), [l(agg_op, [v("R"), v("K"), count]), l(agg_no_value, [v("R"), v("K")])]).
r(r50, l(agg_refused, [v("R"), member_unbound]), [l(agg_inner, [v("R"), v("_$0"), v("I")]), l(unsafe_rule, [v("I")])]).
r(r51, l(agg_refused, [v("R"), unsafe]), [l(agg_op, [v("R"), v("_$0"), v("_$1")]), l(unsafe_rule, [v("R")])]).
r(r52, l(agg_refused, [v("R"), reads_live_kernel]), [l(premise_agg, [v("R"), v("Rel")]), l(live_kernel_rel, [v("Rel")])]).
r(r53, l(agg_refused, [v("R"), key_on_threshold]), [l(agg_op, [v("R"), v("K"), at_least]), l(agg_keyed, [v("R"), v("K")])]).
r(r54, l(agg_refused, [v("R"), threshold_needs_a_term]), [l(agg_op, [v("R"), v("K"), at_least]), l(agg_no_value, [v("R"), v("K")])]).
r(r55, l(thr_read, [v("R"), v("Q")]), [l(agg_op, [v("R"), v("K"), at_least]), l(agg_inner, [v("R"), v("K"), v("I")]), l(premise_lit, [v("I"), v("_$0"), f("$lit", [v("Q"), v("_$1"), v("_$2"), v("_$3")])])]).
r(r56, l(thr_read, [v("R"), v("Q")]), [l(agg_op, [v("R"), v("K"), at_least]), l(agg_inner, [v("R"), v("K"), v("I")]), l(premise_lit, [v("I"), v("_$0"), f("$not", [f("$lit", [v("Q"), v("_$1"), v("_$2"), v("_$3")])])])]).
needs_holistic_key(median).
needs_holistic_key(quantile).
one_value_op(median).
param_op(quantile).
param_op(rank).
r(r57, l(agg_two_terms, [v("R"), v("K")]), [l(premise_lit, [v("R"), v("K"), f("$agg", [v("_$0"), v("_$1"), f("$cons", [v("_$2"), f("$cons", [v("_$3"), $nil])]), v("_$4"), v("_$5")])])]).
r(r58, l(agg_refused, [v("R"), holistic_needs_key]), [l(agg_op, [v("R"), v("K"), v("Op")]), l(needs_holistic_key, [v("Op")]), n(l(agg_keyed, [v("R"), v("K")]))]).
r(r59, l(agg_tuple_rank, [v("R"), v("K")]), [l(agg_op, [v("R"), v("K"), rank]), l(agg_keyed, [v("R"), v("K")])]).
r(r60, l(agg_refused, [v("R"), param_and_value]), [l(agg_op, [v("R"), v("K"), v("Op")]), l(param_op, [v("Op")]), n(l(agg_two_terms, [v("R"), v("K")])), n(l(agg_tuple_rank, [v("R"), v("K")]))]).
r(r61, l(rank_pairs, [v("R"), v("K"), v("A"), v("B")]), [l(agg_tuple_rank, [v("R"), v("K")]), l(premise_lit, [v("R"), v("K"), f("$agg", [v("_$0"), v("_$1"), v("A"), v("B"), v("_$2")])])]).
r(r62, l(rank_pairs, [v("R"), v("K"), v("A"), v("B")]), [l(rank_pairs, [v("R"), v("K"), f("$cons", [v("_$0"), v("A")]), f("$cons", [v("_$1"), v("B")])])]).
r(r63, l(rank_arity_ok, [v("R"), v("K")]), [l(rank_pairs, [v("R"), v("K"), $nil, $nil])]).
r(r64, l(agg_refused, [v("R"), rank_key_arity]), [l(agg_tuple_rank, [v("R"), v("K")]), n(l(rank_arity_ok, [v("R"), v("K")]))]).
r(r65, l(agg_group_var, [v("R"), v("K"), v("V")]), [l(premise_var, [v("R"), v("K"), agg, v("_$0"), v("V")]), n(l(bound_before, [v("R"), v("K"), v("V")]))]).
r(r66, l(agg_groups, [v("R"), v("K")]), [l(agg_group_var, [v("R"), v("K"), v("_$0")])]).
r(r67, l(empty_zero, [v("R"), v("K")]), [l(agg_op, [v("R"), v("K"), count]), n(l(agg_groups, [v("R"), v("K")]))]).
r(r68, l(empty_zero, [v("R"), v("K")]), [l(agg_op, [v("R"), v("K"), sum]), n(l(agg_groups, [v("R"), v("K")]))]).
r(r69, l(member_reader, [v("R")]), [l(analysed, [v("R")]), l(premise_pos, [v("R"), agg_member])]).
r(r70, l(member_reader, [v("R")]), [l(analysed, [v("R")]), l(premise_pos, [v("R"), agg_member_prem])]).
r(r71, l(member_reader, [v("R")]), [l(analysed, [v("R")]), l(premise_neg, [v("R"), agg_member])]).
r(r72, l(member_reader, [v("R")]), [l(analysed, [v("R")]), l(premise_neg, [v("R"), agg_member_prem])]).
r(r73, l(lattice_member_reader, [v("R")]), [l(analysed, [v("R")]), l(premise_pos, [v("R"), lattice_member])]).
r(r74, l(lattice_member_reader, [v("R")]), [l(analysed, [v("R")]), l(premise_pos, [v("R"), lattice_member_prem])]).
r(r75, l(lattice_member_reader, [v("R")]), [l(analysed, [v("R")]), l(premise_neg, [v("R"), lattice_member])]).
r(r76, l(lattice_member_reader, [v("R")]), [l(analysed, [v("R")]), l(premise_neg, [v("R"), lattice_member_prem])]).
r(r77, l(dominated_reader, [v("R")]), [l(analysed, [v("R")]), l(premise_pos, [v("R"), dominated_by])]).
r(r78, l(dominated_reader, [v("R")]), [l(analysed, [v("R")]), l(premise_neg, [v("R"), dominated_by])]).
edb(premise_arith).
edb(lit_arity).
r(r79, l(lattice_rel, [v("P")]), [l(lattice_decl, [v("P"), v("_$0"), v("_$1")])]).
r(r80, l(lattice_any, []), [l(lattice_rel, [v("_$0")])]).
r(r81, l(lat_op, [v("P"), v("Op")]), [l(lattice_decl, [v("P"), v("_$0"), v("Op")])]).
r(r82, l(lattice_refused, [v("P"), not_idempotent]), [l(lattice_decl, [v("P"), v("_$0"), v("Op")]), n(l(idempotent_op, [v("Op")]))]).
r(r83, l(lattice_refused, [v("P"), two_algebras]), [l(lattice_decl, [v("P"), v("_$0"), v("A")]), l(lattice_decl, [v("P"), v("_$1"), v("B")]), b("!=", v("A"), v("B"))]).
r(r84, l(lattice_refused, [v("P"), two_arities]), [l(lattice_decl, [v("P"), v("N"), v("_$0")]), l(lattice_decl, [v("P"), v("M"), v("_$1")]), b("!=", v("N"), v("M"))]).
r(r85, l(agg_refused, [v("R"), lattice_arity]), [l(lit_arity, [v("R"), v("_$0"), v("P"), v("N")]), l(lattice_decl, [v("P"), v("M"), v("_$1")]), b("!=", v("N"), v("M"))]).
edb(dominance).
r(r86, l(sub_rel, [v("P")]), [l(dominance, [v("_$0"), v("P"), v("_$1"), v("_$2")])]).
r(r87, l(lattice_rel, [v("P")]), [l(sub_rel, [v("P")])]).
r(r88, l(lattice_refused, [v("P"), two_algebras]), [l(sub_rel, [v("P")]), l(lattice_decl, [v("P"), v("_$0"), v("_$1")])]).
r(r89, l(lattice_refused, [v("P"), two_arities]), [l(dominance, [v("_$0"), v("P"), v("N"), v("_$1")]), l(dominance, [v("_$2"), v("P"), v("M"), v("_$3")]), b("!=", v("N"), v("M"))]).
r(r90, l(lattice_refused, [v("P"), two_keys]), [l(dominance, [v("_$0"), v("P"), v("_$1"), v("J")]), l(dominance, [v("_$2"), v("P"), v("_$3"), v("K")]), b("!=", v("J"), v("K"))]).
r(r91, l(agg_refused, [v("R"), lattice_arity]), [l(lit_arity, [v("R"), v("_$0"), v("P"), v("N")]), l(dominance, [v("_$1"), v("P"), v("M"), v("_$2")]), b("!=", v("N"), v("M"))]).
r(r92, l(lat_aggval, [v("R"), v("A"), v("V")]), [l(concludes, [v("R"), v("H")]), l(lattice_rel, [v("H")]), l(premise_lit, [v("R"), v("_$0"), f("$agg", [v("A"), f("$var", [v("V")]), v("_$1"), v("_$2"), v("_$3")])])]).
r(r93, l(lat_aggval, [v("R"), v("A"), v("X")]), [l(lat_aggval, [v("R"), v("A"), v("Y")]), l(premise_var, [v("R"), v("J"), right, v("_$0"), v("Y")]), l(premise_lit, [v("R"), v("J"), f("$builtin", [s("is"), v("_$1")])]), l(premise_var, [v("R"), v("J"), left, v("_$2"), v("X")])]).
r(r94, l(lat_aggval, [v("R"), v("A"), v("X")]), [l(lat_aggval, [v("R"), v("A"), v("Y")]), l(premise_var, [v("R"), v("J"), right, v("_$0"), v("Y")]), l(premise_lit, [v("R"), v("J"), f("$builtin", [s("="), v("_$1")])]), l(premise_var, [v("R"), v("J"), left, v("_$2"), v("X")])]).
r(r95, l(lat_aggval, [v("R"), v("A"), v("X")]), [l(lat_aggval, [v("R"), v("A"), v("Y")]), l(premise_var, [v("R"), v("J"), left, v("_$0"), v("Y")]), l(premise_lit, [v("R"), v("J"), f("$builtin", [s("="), v("_$1")])]), l(premise_var, [v("R"), v("J"), right, v("_$2"), v("X")])]).
r(r96, l(agg_refused, [v("R"), lattice_two_algebras]), [l(concludes, [v("R"), v("H")]), l(lat_op, [v("H"), v("Op")]), l(lat_aggval, [v("R"), v("A"), v("V")]), l(premise_var, [v("R"), 0, hval, v("_$0"), v("V")]), b("!=", v("A"), v("Op"))]).
r(r97, l(lat_edge, [v("A"), v("B")]), [l(lattice_any, []), l(concludes, [v("R"), v("A")]), l(conclusion_tense, [v("R"), now]), l(premise_pos, [v("R"), v("B")])]).
r(r98, l(lat_edge, [v("A"), v("B")]), [l(lattice_any, []), l(concludes, [v("R"), v("A")]), l(conclusion_tense, [v("R"), now]), l(premise_neg, [v("R"), v("B")])]).
r(r99, l(lat_edge, [v("A"), v("B")]), [l(lattice_any, []), l(concludes, [v("R"), v("A")]), l(conclusion_tense, [v("R"), now]), l(premise_agg, [v("R"), v("B")])]).
r(r100, l(lat_reach, [v("P"), v("B")]), [l(lattice_rel, [v("P")]), l(lat_edge, [v("P"), v("B")])]).
r(r101, l(lat_reach, [v("P"), v("B")]), [l(lat_reach, [v("P"), v("A")]), l(lat_edge, [v("A"), v("B")])]).
r(r102, l(lat_read, [v("R"), v("K"), v("P")]), [l(premise_lit, [v("R"), v("K"), f("$lit", [v("P"), v("_$0"), v("_$1"), v("_$2")])]), l(lattice_rel, [v("P")])]).
r(r103, l(lat_inner, [v("R"), v("K"), v("P")]), [l(lat_read, [v("R"), v("K"), v("P")]), l(concludes, [v("R"), v("H")]), l(conclusion_tense, [v("R"), now]), l(lat_reach, [v("P"), v("H")])]).
r(r104, l(lattice_outer, [v("R"), v("P")]), [l(lat_read, [v("R"), v("K"), v("P")]), n(l(lat_inner, [v("R"), v("K"), v("P")]))]).
r(r105, l(agg_refused, [v("R"), lattice_negated]), [l(premise_neg, [v("R"), v("P")]), l(lattice_rel, [v("P")]), l(concludes, [v("R"), v("H")]), l(conclusion_tense, [v("R"), now]), l(lat_reach, [v("P"), v("H")])]).
better_move(min, down).
better_move(and, down).
better_move(max, up).
better_move(or, up).
better_move(union, grow_set).
better_move(hull, grow_iv).
better_move(bitor, grow_bits).
order_move(up).
order_move(down).
join_move(grow_set).
join_move(grow_iv).
join_move(grow_bits).
join_read(s("in")).
join_read(s("subset")).
lt_op(s("<")).
lt_op(s("<=")).
gt_op(s(">")).
gt_op(s(">=")).
top_const(up, true).
top_const(down, false).
r(r106, l(lat_taint, [v("R"), v("K"), v("V")]), [l(lat_inner, [v("R"), v("K"), v("_$0")]), l(premise_var, [v("R"), v("K"), lval, v("_$1"), v("V")])]).
r(r107, l(lat_taint, [v("R"), v("K"), v("X")]), [l(lat_taint, [v("R"), v("K"), v("Y")]), l(premise_var, [v("R"), v("J"), right, v("_$0"), v("Y")]), l(premise_lit, [v("R"), v("J"), f("$builtin", [s("is"), v("_$1")])]), l(premise_var, [v("R"), v("J"), left, v("_$2"), v("X")])]).
r(r108, l(lat_taint, [v("R"), v("K"), v("X")]), [l(lat_taint, [v("R"), v("K"), v("Y")]), l(premise_var, [v("R"), v("J"), right, v("_$0"), v("Y")]), l(premise_lit, [v("R"), v("J"), f("$builtin", [s("="), v("_$1")])]), l(premise_var, [v("R"), v("J"), left, v("_$2"), v("X")])]).
r(r109, l(lat_taint, [v("R"), v("K"), v("X")]), [l(lat_taint, [v("R"), v("K"), v("Y")]), l(premise_var, [v("R"), v("J"), left, v("_$0"), v("Y")]), l(premise_lit, [v("R"), v("J"), f("$builtin", [s("="), v("_$1")])]), l(premise_var, [v("R"), v("J"), right, v("_$2"), v("X")])]).
r(r110, l(lat_dirty, [v("R"), v("K"), f("$var", [v("Z")])]), [l(lat_taint, [v("R"), v("K"), v("Z")])]).
r(r111, l(lat_clean, [v("R"), v("K"), v("E")]), [l(lat_inner, [v("R"), v("K"), v("_$0")]), l(premise_arith, [v("R"), v("_$1"), v("_$2"), v("_$3"), v("E"), v("_$4")]), n(l(lat_dirty, [v("R"), v("K"), v("E")]))]).
r(r112, l(lat_clean, [v("R"), v("K"), v("E")]), [l(lat_inner, [v("R"), v("K"), v("_$0")]), l(premise_arith, [v("R"), v("_$1"), v("_$2"), v("_$3"), v("_$4"), v("E")]), n(l(lat_dirty, [v("R"), v("K"), v("E")]))]).
r(r113, l(lat_right_dirty, [v("R"), v("K"), v("J")]), [l(lat_taint, [v("R"), v("K"), v("Z")]), l(premise_var, [v("R"), v("J"), right, v("_$0"), v("Z")])]).
r(r114, l(lat_left_dirty, [v("R"), v("K"), v("J")]), [l(lat_taint, [v("R"), v("K"), v("Z")]), l(premise_var, [v("R"), v("J"), left, v("_$0"), v("Z")])]).
flip(up, down).
flip(down, up).
r(r115, l(lat_mv, [v("R"), v("K"), v("V"), v("M")]), [l(lat_inner, [v("R"), v("K"), v("P")]), l(premise_var, [v("R"), v("K"), lval, v("_$0"), v("V")]), l(lat_op, [v("P"), v("Op")]), l(better_move, [v("Op"), v("M")])]).
r(r116, l(lat_step, [v("R"), v("K"), v("Y"), v("J"), v("X"), v("M")]), [l(lat_mv, [v("R"), v("K"), v("Y"), v("M")]), l(order_move, [v("M")]), l(premise_arith, [v("R"), v("J"), f("$var", [v("X")]), s("+"), f("$var", [v("Y")]), v("E")]), l(lat_clean, [v("R"), v("K"), v("E")])]).
r(r117, l(lat_step, [v("R"), v("K"), v("Y"), v("J"), v("X"), v("M")]), [l(lat_mv, [v("R"), v("K"), v("Y"), v("M")]), l(order_move, [v("M")]), l(premise_arith, [v("R"), v("J"), f("$var", [v("X")]), s("+"), v("E"), f("$var", [v("Y")])]), l(lat_clean, [v("R"), v("K"), v("E")])]).
r(r118, l(lat_step, [v("R"), v("K"), v("Y"), v("J"), v("X"), v("M")]), [l(lat_mv, [v("R"), v("K"), v("Y"), v("M")]), l(order_move, [v("M")]), l(premise_arith, [v("R"), v("J"), f("$var", [v("X")]), s("-"), f("$var", [v("Y")]), v("E")]), l(lat_clean, [v("R"), v("K"), v("E")])]).
r(r119, l(lat_step, [v("R"), v("K"), v("Y"), v("J"), v("X"), v("M2")]), [l(lat_mv, [v("R"), v("K"), v("Y"), v("M")]), l(order_move, [v("M")]), l(premise_arith, [v("R"), v("J"), f("$var", [v("X")]), s("-"), v("E"), f("$var", [v("Y")])]), l(lat_clean, [v("R"), v("K"), v("E")]), l(flip, [v("M"), v("M2")])]).
r(r120, l(lat_step, [v("R"), v("K"), v("Y"), v("J"), v("X"), v("M")]), [l(lat_mv, [v("R"), v("K"), v("Y"), v("M")]), l(premise_arith, [v("R"), v("J"), f("$var", [v("X")]), s("is"), f("$var", [v("Y")]), f("$var", [v("Y")])])]).
r(r121, l(lat_step, [v("R"), v("K"), v("Y"), v("J"), v("X"), v("M")]), [l(lat_mv, [v("R"), v("K"), v("Y"), v("M")]), l(order_move, [v("M")]), l(premise_arith, [v("R"), v("J"), f("$var", [v("X")]), v("Op"), f("$var", [v("Y")]), v("E")]), l(minmax, [v("Op")]), l(lat_clean, [v("R"), v("K"), v("E")])]).
r(r122, l(lat_step, [v("R"), v("K"), v("Y"), v("J"), v("X"), v("M")]), [l(lat_mv, [v("R"), v("K"), v("Y"), v("M")]), l(order_move, [v("M")]), l(premise_arith, [v("R"), v("J"), f("$var", [v("X")]), v("Op"), v("E"), f("$var", [v("Y")])]), l(minmax, [v("Op")]), l(lat_clean, [v("R"), v("K"), v("E")])]).
minmax(s("min")).
minmax(s("max")).
tag_step(s("$tropical")).
tag_step(s("$viterbi")).
tag_step(s("$trust")).
r(r123, l(lat_step, [v("R"), v("K"), v("Y"), v("J"), v("X"), v("M")]), [l(lat_mv, [v("R"), v("K"), v("Y"), v("M")]), l(order_move, [v("M")]), l(premise_arith, [v("R"), v("J"), f("$var", [v("X")]), v("Op"), f("$var", [v("Y")]), v("E")]), l(tag_step, [v("Op")]), l(lat_clean, [v("R"), v("K"), v("E")])]).
r(r124, l(lat_step, [v("R"), v("K"), v("Y"), v("J"), v("X"), v("M")]), [l(lat_mv, [v("R"), v("K"), v("Y"), v("M")]), l(order_move, [v("M")]), l(premise_arith, [v("R"), v("J"), f("$var", [v("X")]), v("Op"), v("E"), f("$var", [v("Y")])]), l(tag_step, [v("Op")]), l(lat_clean, [v("R"), v("K"), v("E")])]).
r(r125, l(lat_mv, [v("R"), v("K"), v("X"), v("M")]), [l(lat_step, [v("R"), v("K"), v("_$0"), v("_$1"), v("X"), v("M")])]).
r(r126, l(lat_ok, [v("R"), v("K"), v("V"), v("K"), pos]), [l(lat_inner, [v("R"), v("K"), v("_$0")]), l(premise_var, [v("R"), v("K"), lval, v("_$1"), v("V")])]).
r(r127, l(lat_ok, [v("R"), v("K"), v("V"), v("K"), lval]), [l(lat_inner, [v("R"), v("K"), v("_$0")]), l(premise_var, [v("R"), v("K"), lval, v("_$1"), v("V")])]).
r(r128, l(lat_ok, [v("R"), v("K"), v("Y"), v("J"), right]), [l(lat_step, [v("R"), v("K"), v("Y"), v("J"), v("_$0"), v("_$1")])]).
r(r129, l(lat_ok, [v("R"), v("K"), v("X"), v("J"), left]), [l(lat_step, [v("R"), v("K"), v("_$0"), v("J"), v("X"), v("_$1")])]).
r(r130, l(lat_ok, [v("R"), v("K"), v("X"), v("J"), left]), [l(lat_mv, [v("R"), v("K"), v("X"), down]), l(premise_lit, [v("R"), v("J"), f("$builtin", [v("Op"), f("$cons", [f("$var", [v("X")]), v("_$0")])])]), l(lt_op, [v("Op")]), n(l(lat_right_dirty, [v("R"), v("K"), v("J")]))]).
r(r131, l(lat_ok, [v("R"), v("K"), v("X"), v("J"), left]), [l(lat_mv, [v("R"), v("K"), v("X"), up]), l(premise_lit, [v("R"), v("J"), f("$builtin", [v("Op"), f("$cons", [f("$var", [v("X")]), v("_$0")])])]), l(gt_op, [v("Op")]), n(l(lat_right_dirty, [v("R"), v("K"), v("J")]))]).
r(r132, l(lat_ok, [v("R"), v("K"), v("X"), v("J"), right]), [l(lat_mv, [v("R"), v("K"), v("X"), up]), l(premise_lit, [v("R"), v("J"), f("$builtin", [v("Op"), f("$cons", [v("_$0"), f("$cons", [f("$var", [v("X")]), $nil])])])]), l(lt_op, [v("Op")]), n(l(lat_left_dirty, [v("R"), v("K"), v("J")]))]).
r(r133, l(lat_ok, [v("R"), v("K"), v("X"), v("J"), right]), [l(lat_mv, [v("R"), v("K"), v("X"), down]), l(premise_lit, [v("R"), v("J"), f("$builtin", [v("Op"), f("$cons", [v("_$0"), f("$cons", [f("$var", [v("X")]), $nil])])])]), l(gt_op, [v("Op")]), n(l(lat_left_dirty, [v("R"), v("K"), v("J")]))]).
r(r134, l(lat_ok, [v("R"), v("K"), v("X"), v("J"), left]), [l(lat_mv, [v("R"), v("K"), v("X"), v("M")]), l(top_const, [v("M"), v("C")]), l(premise_lit, [v("R"), v("J"), f("$builtin", [s("="), f("$cons", [f("$var", [v("X")]), f("$cons", [v("C"), $nil])])])])]).
r(r135, l(lat_ok, [v("R"), v("K"), v("X"), v("J"), right]), [l(lat_mv, [v("R"), v("K"), v("X"), v("M")]), l(top_const, [v("M"), v("C")]), l(premise_lit, [v("R"), v("J"), f("$builtin", [s("="), f("$cons", [v("C"), f("$cons", [f("$var", [v("X")]), $nil])])])])]).
r(r136, l(lat_ok, [v("R"), v("K"), v("X"), v("J"), right]), [l(lat_mv, [v("R"), v("K"), v("X"), v("M")]), l(join_move, [v("M")]), l(premise_lit, [v("R"), v("J"), f("$builtin", [v("Op"), f("$cons", [v("_$0"), f("$cons", [f("$var", [v("X")]), $nil])])])]), l(join_read, [v("Op")]), n(l(lat_left_dirty, [v("R"), v("K"), v("J")]))]).
r(r137, l(lat_head_ok, [v("R"), v("K"), v("X")]), [l(lat_mv, [v("R"), v("K"), v("X"), v("M")]), l(concludes, [v("R"), v("H")]), l(lat_op, [v("H"), v("Op")]), l(better_move, [v("Op"), v("M")]), l(premise_var, [v("R"), 0, hval, v("_$0"), v("X")])]).
r(r138, l(lat_ok, [v("R"), v("K"), v("X"), 0, head]), [l(lat_head_ok, [v("R"), v("K"), v("X")])]).
r(r139, l(lat_ok, [v("R"), v("K"), v("X"), 0, hval]), [l(lat_head_ok, [v("R"), v("K"), v("X")])]).
edb(lattice_widen).
r(r140, l(lat_widened, [v("P")]), [l(lattice_widen, [v("P"), v("_$0")])]).
widenable(hull).
r(r141, l(lattice_refused, [v("P"), widen_not_hull]), [l(lattice_widen, [v("P"), v("_$0")]), l(lat_op, [v("P"), v("Op")]), n(l(widenable, [v("Op")]))]).
r(r142, l(lattice_refused, [v("P"), two_widenings]), [l(lattice_widen, [v("P"), v("A")]), l(lattice_widen, [v("P"), v("B")]), b("!=", v("A"), v("B"))]).
iv_op(s("ivadd")).
iv_op(s("ivsub")).
iv_op(s("ivmul")).
iv_op(s("ivmeet")).
r(r143, l(lat_step, [v("R"), v("K"), v("Y"), v("J"), v("X"), grow_iv]), [l(lat_mv, [v("R"), v("K"), v("Y"), grow_iv]), l(premise_arith, [v("R"), v("J"), f("$var", [v("X")]), v("Op"), f("$var", [v("Y")]), v("E")]), l(iv_op, [v("Op")]), l(lat_clean, [v("R"), v("K"), v("E")])]).
r(r144, l(lat_step, [v("R"), v("K"), v("Y"), v("J"), v("X"), grow_iv]), [l(lat_mv, [v("R"), v("K"), v("Y"), grow_iv]), l(premise_arith, [v("R"), v("J"), f("$var", [v("X")]), v("Op"), v("E"), f("$var", [v("Y")])]), l(iv_op, [v("Op")]), b("!=", v("Op"), s("ivmul")), l(lat_clean, [v("R"), v("K"), v("E")])]).
r(r145, l(lat_iv_step, [v("R"), v("K")]), [l(lat_step, [v("R"), v("K"), v("_$0"), v("J"), v("_$1"), grow_iv]), l(premise_arith, [v("R"), v("J"), v("_$2"), v("Op"), v("_$3"), v("_$4")]), l(iv_op, [v("Op")])]).
r(r146, l(unw_edge, [v("A"), v("B")]), [l(lat_edge, [v("A"), v("B")]), n(l(lat_widened, [v("A")])), n(l(lat_widened, [v("B")]))]).
r(r147, l(unw_reach, [v("A"), v("B")]), [l(unw_edge, [v("A"), v("B")])]).
r(r148, l(unw_reach, [v("A"), v("C")]), [l(unw_reach, [v("A"), v("B")]), l(unw_edge, [v("B"), v("C")])]).
r(r149, l(agg_refused, [v("R"), lattice_unwidened]), [l(lat_iv_step, [v("R"), v("K")]), l(lat_inner, [v("R"), v("K"), v("P")]), l(concludes, [v("R"), v("H")]), l(unw_reach, [v("P"), v("H")])]).
r(r150, l(agg_refused, [v("R"), lattice_unwidened]), [l(lat_iv_step, [v("R"), v("K")]), l(lat_inner, [v("R"), v("K"), v("H")]), l(concludes, [v("R"), v("H")]), n(l(lat_widened, [v("H")]))]).
r(r151, l(lat_use, [v("R"), v("K"), v("X"), v("J"), v("S")]), [l(lat_taint, [v("R"), v("K"), v("X")]), l(premise_var, [v("R"), v("J"), v("S"), v("_$0"), v("X")])]).
r(r152, l(lat_misuse, [v("R")]), [l(lat_use, [v("R"), v("K"), v("X"), v("J"), v("S")]), n(l(lat_ok, [v("R"), v("K"), v("X"), v("J"), v("S")]))]).
r(r153, l(lat_args, [v("R"), v("K"), v("L")]), [l(lat_inner, [v("R"), v("K"), v("_$0")]), l(premise_lit, [v("R"), v("K"), f("$lit", [v("_$1"), v("_$2"), v("L"), v("_$3")])])]).
r(r154, l(lat_args, [v("R"), v("K"), v("T")]), [l(lat_args, [v("R"), v("K"), f("$cons", [v("_$0"), v("T")])])]).
r(r155, l(lat_last, [v("R"), v("K"), v("X")]), [l(lat_args, [v("R"), v("K"), f("$cons", [v("X"), $nil])])]).
r(r156, l(lat_last_var, [v("R"), v("K")]), [l(lat_last, [v("R"), v("K"), f("$var", [v("_$0")])])]).
r(r157, l(lat_const_ok, [v("R"), v("K")]), [l(lat_inner, [v("R"), v("K"), v("P")]), l(lat_last, [v("R"), v("K"), v("C")]), l(lat_op, [v("P"), v("Op")]), l(better_move, [v("Op"), v("M")]), l(top_const, [v("M"), v("C")])]).
r(r158, l(lat_misuse, [v("R")]), [l(lat_inner, [v("R"), v("K"), v("P")]), l(lat_op, [v("P"), v("_$0")]), n(l(lat_last_var, [v("R"), v("K")])), n(l(lat_const_ok, [v("R"), v("K")]))]).
r(r159, l(agg_refused, [v("R"), lattice_nonmonotone]), [l(lat_misuse, [v("R")]), n(l(ord_rule, [v("R")]))]).
r(r160, l(agg_refused, [v("R"), order_nonmonotone]), [l(lat_misuse, [v("R")]), l(ord_rule, [v("R")])]).
edb(order_comp).
edb(order_bad_read).
r(r161, l(ord_rel, [v("P")]), [l(order_comp, [v("P"), v("_$0"), v("_$1"), v("_$2"), v("_$3")])]).
r(r162, l(ord_owned, [v("P"), v("R")]), [l(order_comp, [v("P"), v("_$0"), v("_$1"), v("_$2"), v("R")])]).
r(r163, l(lattice_refused, [v("P"), order_and_rules]), [l(ord_rel, [v("P")]), l(dominance, [v("R"), v("P"), v("_$0"), v("_$1")]), n(l(ord_owned, [v("P"), v("R")]))]).
r(r164, l(lattice_refused, [v("P"), two_orders]), [l(order_comp, [v("P"), v("K1"), v("_$0"), v("_$1"), v("_$2")]), l(order_comp, [v("P"), v("K2"), v("_$3"), v("_$4"), v("_$5")]), b("!=", v("K1"), v("K2"))]).
r(r165, l(lattice_refused, [v("P"), two_orders]), [l(order_comp, [v("P"), v("_$0"), v("I"), v("D1"), v("_$1")]), l(order_comp, [v("P"), v("_$2"), v("I"), v("D2"), v("_$3")]), b("!=", v("D1"), v("D2"))]).
r(r166, l(lat_taint, [v("R"), v("K"), v("V")]), [l(lat_inner, [v("R"), v("K"), v("P")]), l(ord_rel, [v("P")]), l(premise_var, [v("R"), v("K"), oval, v("_$0"), v("V")])]).
r(r167, l(lat_mv, [v("R"), v("K"), v("V"), v("M")]), [l(lat_inner, [v("R"), v("K"), v("P")]), l(premise_var, [v("R"), v("K"), oval, v("I"), v("V")]), l(order_comp, [v("P"), v("_$0"), v("I"), v("Dir"), v("_$1")]), l(better_move, [v("Dir"), v("M")])]).
r(r168, l(lat_ok, [v("R"), v("K"), v("V"), v("K"), oval]), [l(lat_inner, [v("R"), v("K"), v("P")]), l(ord_rel, [v("P")]), l(premise_var, [v("R"), v("K"), oval, v("_$0"), v("V")])]).
r(r169, l(lat_ok, [v("R"), v("K"), v("V"), v("K"), pos]), [l(lat_inner, [v("R"), v("K"), v("P")]), l(ord_rel, [v("P")]), l(premise_var, [v("R"), v("K"), oval, v("_$0"), v("V")])]).
r(r170, l(lat_misuse, [v("R")]), [l(lat_inner, [v("R"), v("K"), v("P")]), l(ord_rel, [v("P")]), l(order_bad_read, [v("R"), v("K")])]).
r(r171, l(ord_head_dir, [v("R"), v("K"), v("X"), v("I")]), [l(premise_var, [v("R"), 0, oval, v("I"), v("X")]), l(concludes, [v("R"), v("H")]), l(order_comp, [v("H"), v("_$0"), v("I"), v("Dir"), v("_$1")]), l(lat_mv, [v("R"), v("K"), v("X"), v("M")]), l(better_move, [v("Dir"), v("M")])]).
r(r172, l(ord_head_unfit, [v("R"), v("K"), v("X")]), [l(lat_taint, [v("R"), v("K"), v("X")]), l(premise_var, [v("R"), 0, oval, v("I"), v("X")]), n(l(ord_head_dir, [v("R"), v("K"), v("X"), v("I")]))]).
r(r173, l(lat_ok, [v("R"), v("K"), v("X"), 0, oval]), [l(lat_taint, [v("R"), v("K"), v("X")]), l(premise_var, [v("R"), 0, oval, v("_$0"), v("X")]), n(l(ord_head_unfit, [v("R"), v("K"), v("X")]))]).
r(r174, l(lat_ok, [v("R"), v("K"), v("X"), 0, head]), [l(lat_ok, [v("R"), v("K"), v("X"), 0, oval])]).
r(r175, l(lat_base, [v("R"), v("K"), v("V"), v("I")]), [l(lat_inner, [v("R"), v("K"), v("P")]), l(ord_rel, [v("P")]), l(premise_var, [v("R"), v("K"), oval, v("I"), v("V")])]).
r(r176, l(lat_base, [v("R"), v("K"), v("V"), 1]), [l(lat_inner, [v("R"), v("K"), v("P")]), n(l(ord_rel, [v("P")])), l(premise_var, [v("R"), v("K"), lval, v("_$0"), v("V")])]).
r(r177, l(ord_org, [v("R"), v("K"), v("V"), v("I")]), [l(lat_base, [v("R"), v("K"), v("V"), v("I")])]).
r(r178, l(ord_org, [v("R"), v("K"), v("X"), v("I")]), [l(ord_org, [v("R"), v("K"), v("Y"), v("I")]), l(lat_step, [v("R"), v("K"), v("Y"), v("_$0"), v("X"), v("_$1")])]).
r(r179, l(strict_step, [v("R"), v("J")]), [l(premise_arith, [v("R"), v("J"), v("_$0"), s("+"), v("_$1"), v("_$2")])]).
r(r180, l(strict_step, [v("R"), v("J")]), [l(premise_arith, [v("R"), v("J"), v("_$0"), s("-"), v("_$1"), v("_$2")])]).
r(r181, l(strict_step, [v("R"), v("J")]), [l(premise_arith, [v("R"), v("J"), f("$var", [v("X")]), s("is"), f("$var", [v("Y")]), f("$var", [v("Y")])])]).
r(r182, l(ord_str, [v("R"), v("K"), v("V")]), [l(lat_base, [v("R"), v("K"), v("V"), v("_$0")])]).
r(r183, l(ord_str, [v("R"), v("K"), v("X")]), [l(ord_str, [v("R"), v("K"), v("Y")]), l(lat_step, [v("R"), v("K"), v("Y"), v("J"), v("X"), v("_$0")]), l(strict_step, [v("R"), v("J")])]).
r(r184, l(ord_has_org, [v("R"), v("K"), v("X")]), [l(ord_org, [v("R"), v("K"), v("X"), v("_$0")])]).
r(r185, l(lex_rel, [v("P")]), [l(order_comp, [v("P"), lex, v("_$0"), v("_$1"), v("_$2")])]).
r(r186, l(lex_head, [v("R")]), [l(concludes, [v("R"), v("H")]), l(lex_rel, [v("H")])]).
r(r187, l(lex_late, [v("R"), v("K"), v("X")]), [l(lat_inner, [v("R"), v("K"), v("P")]), l(lex_rel, [v("P")]), l(ord_org, [v("R"), v("K"), v("X"), v("I")]), b(">", v("I"), 1)]).
ord_cmp(s("<")).
ord_cmp(s("<=")).
ord_cmp(s(">")).
ord_cmp(s(">=")).
ord_cmp(s("=")).
ord_cmp(s("!=")).
r(r188, l(lat_misuse, [v("R")]), [l(lex_late, [v("R"), v("K"), v("X")]), l(premise_lit, [v("R"), v("J"), f("$builtin", [v("Op"), v("_$0")])]), l(premise_var, [v("R"), v("J"), v("_$1"), v("_$2"), v("X")]), l(ord_cmp, [v("Op")])]).
r(r189, l(lat_misuse, [v("R")]), [l(lex_late, [v("R"), v("K"), v("X")]), l(premise_var, [v("R"), 0, hval, v("_$0"), v("X")])]).
r(r190, l(lat_misuse, [v("R")]), [l(lex_late, [v("R"), v("K"), v("X")]), l(premise_var, [v("R"), 0, oval, v("_$0"), v("X")]), l(concludes, [v("R"), v("H")]), n(l(lex_rel, [v("H")]))]).
r(r191, l(ord_more, [v("P"), v("I")]), [l(order_comp, [v("P"), v("_$0"), v("I"), v("_$1"), v("_$2")]), l(order_comp, [v("P"), v("_$3"), v("J"), v("_$4"), v("_$5")]), b(">", v("J"), v("I"))]).
r(r192, l(lex_pos, [v("R"), v("I")]), [l(concludes, [v("R"), v("H")]), l(lex_rel, [v("H")]), l(ord_more, [v("H"), v("I")])]).
r(r193, l(lex_track, [v("R"), v("K")]), [l(lex_head, [v("R")]), l(premise_var, [v("R"), 0, oval, v("_$0"), v("X")]), l(lat_taint, [v("R"), v("K"), v("X")])]).
r(r194, l(lex_strict, [v("R"), v("K"), v("I")]), [l(premise_var, [v("R"), 0, oval, v("I"), v("X")]), l(ord_org, [v("R"), v("K"), v("X"), v("I")]), l(ord_str, [v("R"), v("K"), v("X")])]).
r(r195, l(lat_misuse, [v("R")]), [l(lex_track, [v("R"), v("K")]), l(lex_pos, [v("R"), v("I")]), n(l(lex_strict, [v("R"), v("K"), v("I")]))]).
r(r196, l(lat_misuse, [v("R")]), [l(lex_head, [v("R")]), l(premise_var, [v("R"), 0, oval, v("_$0"), v("X")]), l(lat_taint, [v("R"), v("K"), v("X")]), n(l(ord_has_org, [v("R"), v("K"), v("X")]))]).
r(r197, l(ord_rule, [v("R")]), [l(lat_inner, [v("R"), v("_$0"), v("P")]), l(ord_rel, [v("P")])]).
r(r198, l(ord_rule, [v("R")]), [l(concludes, [v("R"), v("H")]), l(ord_rel, [v("H")])]).
r(r199, l(lat_live, [v("P"), v("P")]), [l(lattice_rel, [v("P")])]).
r(r200, l(lat_live, [v("A"), v("P")]), [l(lattice_any, []), l(concludes, [v("R"), v("A")]), l(conclusion_tense, [v("R"), now]), l(premise_pos, [v("R"), v("B")]), n(l(lattice_rel, [v("B")])), l(lat_live, [v("B"), v("P")])]).
r(r201, l(lat_live, [v("A"), v("P")]), [l(lat_inner, [v("R"), v("_$0"), v("B")]), l(concludes, [v("R"), v("A")]), l(lat_live, [v("B"), v("P")])]).
r(r202, l(agg_refused, [v("R"), threshold_lattice]), [l(thr_read, [v("R"), v("Q")]), l(lat_live, [v("Q"), v("_$0")])]).
r(r203, l(agg_refused, [v("R"), threshold_lattice]), [l(agg_op, [v("R"), v("_$0"), at_least]), l(concludes, [v("R"), v("H")]), l(lattice_rel, [v("H")])]).
r(r204, l(agg_refused, [v("R"), threshold_lattice]), [l(agg_op, [v("R"), v("_$0"), at_least]), l(lat_inner, [v("R"), v("_$1"), v("_$2")])]).
stratum(analysed, 1).
stratum(slot, 1).
stratum(binds_at, 1).
stratum(bound_before, 1).
stratum(ground_upto, 1).
stratum(ground, 1).
stratum(binds, 1).
stratum(op_used, 1).
stratum(cmp_op, 1).
stratum(blocked_head, 1).
stratum(has_neg_rule, 1).
stratum(neg_relation, 1).
stratum(provenance_reader, 1).
stratum(agg_op, 1).
stratum(agg_keyed, 1).
stratum(agg_one_value, 1).
stratum(agg_no_value, 1).
stratum(agg_two_terms, 1).
stratum(agg_tuple_rank, 1).
stratum(rank_pairs, 1).
stratum(rank_arity_ok, 1).
stratum(thr_read, 1).
stratum(has_agg_rule, 1).
stratum(member_reader, 1).
stratum(unsafe_rule, 2).
stratum(executable, 2).
stratum(demand_rel, 2).
stratum(trigger_of, 2).
stratum(agg_group_var, 2).
stratum(agg_groups, 2).
stratum(agg_refused, 5).
stratum(mono_rule, 3).
stratum(stratum_cone, 3).
stratum(late_rule, 3).
stratum(empty_zero, 3).
stratum(lat_aggval, 1).
stratum(lat_args, 1).
stratum(lat_const_ok, 1).
stratum(lat_dirty, 1).
stratum(lat_edge, 1).
stratum(lat_inner, 1).
stratum(lat_last, 1).
stratum(lat_last_var, 1).
stratum(lat_left_dirty, 1).
stratum(lat_op, 1).
stratum(lat_reach, 1).
stratum(lat_read, 1).
stratum(lat_right_dirty, 1).
stratum(lat_taint, 1).
stratum(lat_use, 1).
stratum(lattice_any, 1).
stratum(lattice_member_reader, 1).
stratum(lattice_refused, 2).
stratum(lattice_rel, 1).
stratum(sub_rel, 1).
stratum(dominated_reader, 1).
stratum(lat_widened, 1).
stratum(lat_clean, 2).
stratum(lat_head_ok, 2).
stratum(lat_mv, 2).
stratum(lat_ok, 4).
stratum(lat_step, 2).
stratum(lattice_outer, 2).
stratum(lat_live, 2).
stratum(lat_iv_step, 2).
stratum(unw_edge, 2).
stratum(unw_reach, 2).
stratum(lat_misuse, 5).
stratum(ord_rel, 1).
stratum(ord_owned, 1).
stratum(ord_head_dir, 2).
stratum(ord_head_unfit, 3).
stratum(lat_base, 2).
stratum(ord_org, 2).
stratum(strict_step, 1).
stratum(ord_str, 2).
stratum(ord_has_org, 2).
stratum(lex_rel, 1).
stratum(lex_head, 1).
stratum(lex_late, 2).
stratum(lex_track, 1).
stratum(ord_more, 1).
stratum(lex_pos, 1).
stratum(lex_strict, 2).
stratum(ord_rule, 1).
`;

export const SHRUG_DENSE = `edb(shrug_reason).
edb(shrug_cause).
shrug_reason(budget, s("the evaluation ran out of steps or rows before it could answer")).
shrug_reason(fault, s("a builtin or a fold could not compute a value")).
shrug_reason(divergence, s("a value kept improving around a cycle and never settled")).
shrug_reason(paradox, s("the answer rests on its own negation and is undefined")).
shrug_reason(conflict, s("two answers were given for one key, or two books disagree")).
shrug_reason(federation, s("the answer lives in a volume or book that is not loaded")).
shrug_reason(widened, s("a declared widening enclosed the value: the least value lies within it, and is not known")).
shrug_reason(inherited, s("the answer reads another answer that is a shrug")).
shrug_reason(given, s("a book states that it is not known")).
shrug_cause(budget_exhausted, budget, s("the step budget ran out")).
shrug_cause(space_exhausted, budget, s("the row budget ran out")).
shrug_cause(arith_overflow, fault, s("arithmetic left the integer range of plus or minus 2^60")).
shrug_cause(arith_type_error, fault, s("arithmetic on a value that is not a number")).
shrug_cause(arith_zero_divisor, fault, s("a division by zero")).
shrug_cause(str_type_error, fault, s("a string builtin read a value that is not a string")).
shrug_cause(str_index_error, fault, s("a string builtin read past the end of its string")).
shrug_cause(str_empty_separator, fault, s("a string was split on an empty separator")).
shrug_cause(atom_unwritable, fault, s("a name no atom can carry")).
shrug_cause(agg_overflow, fault, s("an aggregate's total left the integer range")).
shrug_cause(agg_type_error, fault, s("an aggregate folded a value of the wrong type")).
shrug_cause(agg_open_member, fault, s("an aggregate's member could not be computed")).
shrug_cause(set_type_error, fault, s("a membership or subset test read a value that is not a set, an interval or a bitset")).
shrug_cause(tag_off_carrier, fault, s("a semiring tag outside its carrier: viterbi and trust hold integers of [0, 1000000], counting integers of at least 1")).
shrug_cause(unbounded_members, fault, s("the members of an interval with an infinite end were enumerated")).
shrug_cause(widening_forced, widened, s("a lattice cell improved past its declared widening and was widened")).
shrug_cause(regions_capped, budget, s("the values a labeled unknown could be told apart by passed the cap, so the group was not decided by them")).
shrug_cause(demand_cycle, budget, s("a call answered on demand came round again inside its own unfolding, and was not unfolded again")).
shrug_cause(improving_cycle, divergence, s("a lattice value came back through its own improvement")).
shrug_cause(dominance_cycle, conflict, s("a subsumptive value dominates itself, or two dominate each other, so the dominance is no order and the front is not decided")).
shrug_cause(dominance_intransitive, conflict, s("a subsumptive value is dominated by one that no member of the front dominates, or dominates a member, so the dominance is not transitive and the front is not decided")).
shrug_cause(undefined, paradox, s("the alternating fixpoint left it undefined")).
shrug_cause(stated, given, s("the book asserted unknown of it as a fact; the alternating fixpoint did not leave it undefined")).
shrug_cause(concluded, given, s("a rule of the book concluded unknown of it; the alternating fixpoint did not leave it undefined")).
shrug_cause(support_withdrawn, inherited, s("a premise it read is a shrug")).
shrug_cause(fault_left_out, inherited, s("a shrug at the tick before kept it from being staged")).
shrug_cause(left_out_below, inherited, s("the world below has no answer for it")).
shrug_cause(cooled_to_disk, federation, s("the volume was cooled to disk and is not loaded")).
shrug_cause(reflection_sealed, federation, s("the relation is sealed in this world and lives only in the volume that keeps it")).
`;
