// src/kernel-dense.ts — GENERATED by scripts/build_kernel_dense.ts.
//
// The kernel's two programs, compiled into the dense form src/dense.ts reads.
// policy.rofl and safety.rofl are the source; regenerate with
// `npm run build:dense` and test/kernel-policy-program.test.ts checks that you
// did. Nothing here is written by hand.
//
// WHY THIS FILE EXISTS: until 2026-09-06 the kernel carried these as source
// text and called `parseProgram` on them the first time any store with rules
// was evaluated -- which made the 262-line surface parser load-bearing for the
// evaluator itself. Measured: a host that loads only dense facts entered 195
// of the parser's 262 lines, and 168 of those were this parse.

export const POLICY_DENSE = `r(r1, l(rule_reads, [v("A"), v("B")]), [l(concludes, [v("R"), v("A")]), l(premise_pos, [v("R"), v("B")])]).
r(r2, l(rule_reads, [v("A"), v("B")]), [l(concludes, [v("R"), v("A")]), l(premise_neg, [v("R"), v("B")])]).
r(r3, l(rule_relation, [v("A")]), [l(concludes, [v("R"), v("A")])]).
r(r4, l(rule_relation, [v("B")]), [l(rule_reads, [v("A"), v("B")])]).
r(r5, l(cone, [v("A"), v("A")]), [l(rule_relation, [v("A")])]).
r(r6, l(cone, [v("A"), v("C")]), [l(cone, [v("A"), v("B")]), l(rule_reads, [v("B"), v("C")])]).
edb(opaque_seed).
r(r7, l(opaque_closed, [v("A")]), [l(opaque_seed, [v("A")])]).
r(r8, l(opaque_closed, [v("A")]), [l(rule_reads, [v("A"), v("B")]), l(opaque_closed, [v("B")])]).
`;

export const SAFETY_DENSE = `edb(premise_var).
edb(slot_arity).
r(r1, l(slot, [v("R"), v("K"), left]), [l(premise_lit, [v("R"), v("K"), f("$builtin", [v("_$0"), v("_$1")])])]).
r(r2, l(slot, [v("R"), v("K"), right]), [l(premise_lit, [v("R"), v("K"), f("$builtin", [v("_$0"), v("_$1")])])]).
r(r3, l(binds_at, [v("R"), v("K"), v("V")]), [l(premise_var, [v("R"), v("K"), pos, v("_$0"), v("V")])]).
r(r4, l(binds_at, [v("R"), v("K"), v("V")]), [l(premise_lit, [v("R"), v("K"), f("$builtin", [s("is"), v("_$0")])]), l(ground, [v("R"), v("K"), right]), l(premise_var, [v("R"), v("K"), left, v("_$1"), v("V")])]).
r(r5, l(binds_at, [v("R"), v("K"), v("V")]), [l(premise_lit, [v("R"), v("K"), f("$builtin", [s("="), v("_$0")])]), l(ground, [v("R"), v("K"), left]), l(premise_var, [v("R"), v("K"), right, v("_$1"), v("V")])]).
r(r6, l(binds_at, [v("R"), v("K"), v("V")]), [l(premise_lit, [v("R"), v("K"), f("$builtin", [s("="), v("_$0")])]), l(ground, [v("R"), v("K"), right]), l(premise_var, [v("R"), v("K"), left, v("_$1"), v("V")])]).
r(r7, l(bound_before, [v("R"), v("K"), v("V")]), [l(binds_at, [v("R"), v("J"), v("V")]), b("is", v("K"), f("+", [v("J"), 1])), l(has_premise, [v("R"), v("K")])]).
r(r8, l(bound_before, [v("R"), v("K"), v("V")]), [l(bound_before, [v("R"), v("J"), v("V")]), b("is", v("K"), f("+", [v("J"), 1])), l(has_premise, [v("R"), v("K")])]).
r(r9, l(ground_upto, [v("R"), v("K"), v("S"), 0]), [l(slot, [v("R"), v("K"), v("S")])]).
r(r10, l(ground_upto, [v("R"), v("K"), v("S"), v("I")]), [l(ground_upto, [v("R"), v("K"), v("S"), v("J")]), b("is", v("I"), f("+", [v("J"), 1])), l(premise_var, [v("R"), v("K"), v("S"), v("I"), v("V")]), l(bound_before, [v("R"), v("K"), v("V")])]).
r(r11, l(ground, [v("R"), v("K"), v("S")]), [l(ground_upto, [v("R"), v("K"), v("S"), v("N")]), l(slot_arity, [v("R"), v("K"), v("S"), v("N")])]).
r(r12, l(analysed, [v("R")]), [l(slot_arity, [v("R"), 0, head, v("_$0")])]).
r(r13, l(binds, [v("R"), v("V")]), [l(binds_at, [v("R"), v("_$0"), v("V")])]).
eq_or_is(s("=")).
eq_or_is(s("is")).
r(r14, l(op_used, [v("Op")]), [l(premise_lit, [v("_$0"), v("_$1"), f("$builtin", [v("Op"), v("_$2")])])]).
r(r15, l(cmp_op, [v("Op")]), [l(op_used, [v("Op")]), n(l(eq_or_is, [v("Op")]))]).
r(r16, l(unsafe_rule, [v("R")]), [l(premise_var, [v("R"), 0, head, v("_$0"), v("V")]), n(l(binds, [v("R"), v("V")]))]).
r(r17, l(unsafe_rule, [v("R")]), [l(analysed, [v("R")]), l(premise_lit, [v("R"), v("K"), f("$builtin", [s("is"), v("_$0")])]), n(l(ground, [v("R"), v("K"), right]))]).
r(r18, l(unsafe_rule, [v("R")]), [l(analysed, [v("R")]), l(premise_lit, [v("R"), v("K"), f("$builtin", [s("="), v("_$0")])]), n(l(ground, [v("R"), v("K"), left])), n(l(ground, [v("R"), v("K"), right]))]).
r(r19, l(unsafe_rule, [v("R")]), [l(analysed, [v("R")]), l(premise_lit, [v("R"), v("K"), f("$builtin", [v("Op"), v("_$0")])]), l(cmp_op, [v("Op")]), n(l(ground, [v("R"), v("K"), left]))]).
r(r20, l(unsafe_rule, [v("R")]), [l(analysed, [v("R")]), l(premise_lit, [v("R"), v("K"), f("$builtin", [v("Op"), v("_$0")])]), l(cmp_op, [v("Op")]), n(l(ground, [v("R"), v("K"), right]))]).
r(r21, l(blocked_head, [v("R")]), [l(analysed, [v("R")]), l(concludes, [v("R"), v("Rel")]), l(reserved, [v("Rel")])]).
r(r22, l(executable, [v("R")]), [l(analysed, [v("R")]), n(l(blocked_head, [v("R")]))]).
r(r23, l(has_neg_rule, [v("R")]), [l(analysed, [v("R")]), l(premise_neg, [v("R"), v("_$0")])]).
r(r24, l(mono_rule, [v("R")]), [l(executable, [v("R")]), n(l(has_neg_rule, [v("R")])), n(l(unsafe_rule, [v("R")]))]).
stratum_cone(stratum).
r(r25, l(stratum_cone, [v("Rel")]), [l(concludes, [v("R"), v("Rel")]), l(mono_rule, [v("R")]), l(premise_pos, [v("R"), v("Q")]), l(stratum_cone, [v("Q")])]).
r(r26, l(late_rule, [v("R")]), [l(concludes, [v("R"), v("Rel")]), l(mono_rule, [v("R")]), l(stratum_cone, [v("Rel")])]).
r(r27, l(demand_rel, [v("Rel")]), [l(concludes, [v("R"), v("Rel")]), l(conclusion_tense, [v("R"), now]), l(executable, [v("R")]), l(unsafe_rule, [v("R")])]).
r(r28, l(demand_rel, [v("Rel")]), [l(concludes, [v("R"), v("Rel")]), l(conclusion_tense, [v("R"), now]), l(executable, [v("R")]), l(premise_pos, [v("R"), v("Q")]), l(demand_rel, [v("Q")])]).
r(r29, l(trigger_of, [v("P"), v("P")]), [l(analysed, [v("R")]), l(premise_pos, [v("R"), v("P")])]).
r(r30, l(trigger_of, [v("P"), v("X")]), [l(demand_rel, [v("P")]), l(concludes, [v("R"), v("P")]), l(conclusion_tense, [v("R"), now]), l(executable, [v("R")]), l(premise_pos, [v("R"), v("Q")]), l(trigger_of, [v("Q"), v("X")])]).
r(r31, l(neg_relation, [v("A")]), [l(analysed, [v("R")]), l(premise_neg, [v("R"), v("A")])]).
r(r32, l(provenance_reader, [v("R")]), [l(analysed, [v("R")]), l(premise_pos, [v("R"), derived_by])]).
r(r33, l(provenance_reader, [v("R")]), [l(analysed, [v("R")]), l(premise_neg, [v("R"), derived_by])]).
stratum(analysed, 1).
stratum(slot, 1).
stratum(binds_at, 1).
stratum(bound_before, 1).
stratum(ground_upto, 1).
stratum(ground, 1).
stratum(binds, 1).
stratum(op_used, 1).
stratum(cmp_op, 1).
stratum(blocked_head, 1).
stratum(has_neg_rule, 1).
stratum(neg_relation, 1).
stratum(provenance_reader, 1).
stratum(unsafe_rule, 2).
stratum(executable, 2).
stratum(demand_rel, 2).
stratum(trigger_of, 2).
stratum(mono_rule, 3).
stratum(stratum_cone, 3).
stratum(late_rule, 3).
`;
